### ISSUE TITLE
模拟宇宙脚本录制

### ISSUE THREAD

**Issue by Xe-No** [Starry-Wind/StarRailAssistant#211]
### 原因

模拟宇宙自动脚本基本完成，目前大图用的录制脚本，小地图采用的是小地图图标寻路，偶尔会有目标丢失问题，希望能配合录制脚本一起使用，需要有人帮忙录制

### 功能简述

模拟宇宙分支下，temp\Simulated_Universe\map存储了部分地图初始状态，通过截取小地图可以基本识别出这张地图，可以配合已经录制的好的脚本快速跑图

![universe_relax_1](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/18138697/425c1c3c-b636-4ef8-9396-3cefd16109a3)
![universe_21_7](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/18138697/088578e5-04a2-434d-b213-bf673aa27032)

### 功能逻辑

tools下screen_shot.py运行一下可以得到一张相同规格小地图
universeAuto.py下存储了小地图对应的脚本，每张图的操作其实都很少，不会花很多时间
目前要做的都是小图，可能每张图最多三个动作就搞定了

**Comment by esdrtf** [comment]
有后续吗

**Comment by Xe-No** [comment]
没人录，不过隔壁ASU项目功能已经很完善了，直接关闭
