### ISSUE TITLE
[Bug] 转视角幅度不对。get_width或者mouse_move参数有误？

### ISSUE THREAD

**Issue by Klamist** [Starry-Wind/StarRailAssistant#212]
### 问题描述

寻路文件包含mouse_move操作时，转的角度不对

例如3-2_3的开头mouse_move 2200，只转了大概30°，根据路线情况来看，应该转90°。想问下mouse_move在游戏内转90°，期望填写的参数是多少啊……

我使用最新版本的脚本时，get_width获取到2913、1704这两个参数，而在之前我曾正常使用脚本时，我印象中是1280、720左右。我手动修改config里的real_width为1280，并在主程序中禁用get_width步骤，游戏内寻路就是正常的。

### 预期行为

正确寻路

### 实际行为

视角转向未达预期幅度，走错了

### 自动锄大地脚本版本

2.7

### 星穹铁道区服

国服

### 日志

我在get_width.py里加了几个info输出，日志最终如下。

15:34:57 - INFO	| Honkai_Star_Rail.main:23 - 3.1 -  脚本将自动切换至游戏窗口，请保持游戏窗口激活
15:34:57 - INFO	| get_width.get_width:14 - 3.1 -  983870
15:34:57 - INFO	| get_width.get_width:16 - 3.1 -  崩坏：星穹铁道
15:34:57 - INFO	| get_width.get_width:22 - 3.1 -  Original window width and height: 1942 , 1136
15:34:57 - INFO	| get_width.get_width:29 - 3.1 -  DPI in x and y: 144 , 144
15:34:57 - INFO	| get_width.get_width:41 - 3.1 -  Real resolution: 2913 x 1704
15:34:57 - INFO	| Honkai_Star_Rail.main:29 - 3.1 -  开始运行，请勿移动鼠标和键盘
15:34:57 - INFO	| Honkai_Star_Rail.main:30 - 3.1 -  若脚本运行无反应,请使用管理员权限运行
………………

**Comment by Jacheers** [comment]
相同问题。屏幕分辨率2160x1440缩放175%，get_width结果为3402x2002。将缩放调整成100%后get_width得到1920x1080，但仍不能正确转向。手动调整config为1024x768左右时转向正常

**Comment by weiduhuo** [comment]
相同问题。游戏窗口设置为1980x1080全屏，缩放125%，get_width结果为1225x1350。转向幅度过小，不正确。手动给mouse_move数值乘以固定系数1.55后，转向正常。

**Comment by moulai** [comment]
相同问题。

**Comment by htshts1115** [comment]
3-2-3, 3-2-4 遇到相同问题，Real resolution: 2422 x 1408，窗口设置为1920*1080，转向偏小。按前面评论尝试修改尺寸或者mouse_move数值均不对。

**Comment by moulai** [comment]
好像把 `tools/calculated.py` 中，`dx=int(x*1295/real_width)` 改为 `dx=int(x*1295/窗口分辨率)` 如 `dx=int(x*1295/1080)` 就转向正常了。

**Comment by Night-stars-1** [comment]
已经修复
