### ISSUE TITLE
[功能请求] 后台功能

### ISSUE THREAD

**Issue by l497996153** [Starry-Wind/StarRailAssistant#219]
### 原因

可以出个后台功能吗？这就不受鼠标键盘移动，还有游戏必须无覆盖的限制了。

### 功能简述

绑定窗口句柄，鼠键操作还有识图功能后台输入

### 功能逻辑

逻辑和使用方面和前台没区别

### 实现参考

试过csdn上有的一些方法，都不太好使。还在研究当中

**Comment by LuoRenMu** [comment]
我试了一下 好像unity引擎 在窗口不是聚焦的情况下无法进行操作 只会在聚焦的一瞬间执行所有想窗口发送的所有的消息 要实现这方面可能得往模拟器的adb靠了

**Comment by l497996153** [comment]
我也试了下pywinauto，开了管理员模式也没反应。模拟器+adb应该可以，就是感觉好麻烦。还是python简单

**Comment by LuoRenMu** [comment]
现在的pyautogui应该封装一下 如果以后代码多了在换就费力了

**Comment by RogerAbyss** [comment]
可以包在虚拟机里面就不影响了，python也安装好，不懂编程也可以直接开。
