### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Divercrow7** [Starry-Wind/StarRailAssistant#227]
### 问题描述

1. 太卜司环形路线南部的画卷，自动寻路时无法对其自动传送
2. 地图切换至铆钉阵及机械聚落时，没有自动选中该区域

### 预期行为

1. 通过南部平台东边的画卷传送到东南方平台继续
2. 进行一次点击行为选中该区域选项卡，以便进行区域内传送点选择

### 实际行为

1. 实际未能正常对准位置传送，仍在南部平台徘徊
2. 缺少点击行为选中该区域地图，整体卡在地图界面，人工点击一次鼠标选中区域后，可继续正常运行

### 自动锄大地脚本版本

2.7_test

### 星穹铁道区服

国服

### 日志

[日志文件.log](https://github.com/Starry-Wind/Honkai-Star-Rail/files/11505116/default.log)

**Comment by Starry-Wind** [comment]
大部分问题已经在今晚更新地图后解决，入画方面明天处理更新资源即可。太卜司有个地图传送点旁边有个碎片图标请确保你清掉
