### ISSUE TITLE
[路线错误] 3-4-3第一只金人打完后镜头转向问题

### ISSUE THREAD

**Issue by kz-wind** [Starry-Wind/StarRailAssistant#238]
### 问题描述

3-4-3第一只金人打完后镜头转向会改变（与脚本执行时镜头正好相反），后续则无法按照线路继续进行。如果打完第一只金人后重新执行3-4-3线路，则可以全部完成

### 是否使用三月七跑图

- [ ] 是
- [X] 否

### 日志

5:25:54 - INFO	| calculated.auto_map:156 - 3.1 -  开始寻路
15:25:54 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:1/22 {'w': 5.5628745555877686}
15:26:00 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:2/22 {'d': 1.4159743785858154}
15:26:01 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:3/22 {'fighting': 2}
15:26:01 - DEBUG	| calculated.click:30 - 3.1 -  (1594, 579)
15:26:03 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:4/22 {'a': 3.0650529861450195}
15:26:06 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:5/22 {'d': 0.6749937534332275}
15:26:07 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:6/22 {'w': 4.27327618598938}
15:26:11 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:7/22 {'a': 0.6285718441009521}
15:26:12 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:8/22 {'s': 1.8193495273590088}
15:26:13 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:9/22 {'fighting': 1}
15:26:13 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:26:14 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:26:14 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:26:14 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:26:14 - DEBUG	| calculated.click:30 - 3.1 -  (815, 244)
15:26:21 - INFO	| calculated.fighting:134 - 3.1 -  跳过开启自动战斗（沿用设置）
15:27:05 - DEBUG	| calculated.fighting:143 - 3.1 -  (2399, 91)
15:27:05 - INFO	| calculated.fighting:144 - 3.1 -  完成自动战斗
15:27:08 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:10/22 {'w': 1.873732566833496}
15:27:10 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:11/22 {'d': 3.275501012802124}
15:27:13 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:12/22 {'w': 0.9954843521118164}
15:27:14 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:13/22 {'a': 0.4309964179992676}
15:27:15 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:14/22 {'w': 0.952996015548706}
15:27:16 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:15/22 {'d': 2.6657872200012207}
15:27:18 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:16/22 {'w': 2.9321210384368896}
15:27:21 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:17/22 {'a': 0.5538139343261719}
15:27:22 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:18/22 {'fighting': 2}
15:27:22 - DEBUG	| calculated.click:30 - 3.1 -  (1594, 579)
15:27:23 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:19/22 {'w': 2.575901746749878}
15:27:26 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:20/22 {'d': 2.0795013904571533}
15:27:28 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:21/22 {'fighting': 2}
15:27:28 - DEBUG	| calculated.click:30 - 3.1 -  (1594, 579)
15:27:30 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:22/22 {'fighting': 1}

此时手动中断执行

15:28:11 - INFO	| calculated.auto_map:156 - 3.1 -  开始寻路
15:28:11 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:1/22 {'w': 5.5628745555877686}
15:28:17 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:2/22 {'d': 1.4159743785858154}
15:28:18 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:3/22 {'fighting': 2}
15:28:18 - DEBUG	| calculated.click:30 - 3.1 -  (1594, 579)
15:28:20 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:4/22 {'a': 3.0650529861450195}
15:28:23 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:5/22 {'d': 0.6749937534332275}
15:28:24 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:6/22 {'w': 4.27327618598938}
15:28:28 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:7/22 {'a': 0.6285718441009521}
15:28:29 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:8/22 {'s': 1.8193495273590088}
15:28:30 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:9/22 {'fighting': 1}
15:28:30 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:31 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:31 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:31 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:31 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:32 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:32 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:32 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:33 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:33 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:33 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:33 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:34 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:34 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:34 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:34 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:35 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:35 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:35 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:36 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:36 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:36 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:37 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:37 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:37 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:37 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:38 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:38 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:38 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:38 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:39 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:39 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:39 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:39 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:40 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:40 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:40 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:28:41 - INFO	| calculated.fighting:118 - 3.1 -  识别超时,此处可能无敌人
15:28:41 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:10/22 {'w': 1.873732566833496}
15:28:42 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:11/22 {'d': 3.275501012802124}
15:28:46 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:12/22 {'w': 0.9954843521118164}
15:28:47 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:13/22 {'a': 0.4309964179992676}
15:28:47 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:14/22 {'w': 0.952996015548706}
15:28:48 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:15/22 {'d': 2.6657872200012207}
15:28:51 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:16/22 {'w': 2.9321210384368896}
15:28:54 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:17/22 {'a': 0.5538139343261719}
15:28:54 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:18/22 {'fighting': 2}
15:28:54 - DEBUG	| calculated.click:30 - 3.1 -  (1595, 580)
15:28:56 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:19/22 {'w': 2.575901746749878}
15:28:58 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:20/22 {'d': 2.0795013904571533}
15:29:00 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:21/22 {'fighting': 2}
15:29:00 - DEBUG	| calculated.click:30 - 3.1 -  (1594, 579)
15:29:02 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-4_3文件:22/22 {'fighting': 1}
15:29:02 - INFO	| calculated.fighting:111 - 3.1 -  识别中
15:29:02 - DEBUG	| calculated.click:30 - 3.1 -  (1424, 934)
15:29:09 - INFO	| calculated.fighting:134 - 3.1 -  跳过开启自动战斗（沿用设置）
15:29:49 - DEBUG	| calculated.fighting:143 - 3.1 -  (2399, 91)
15:29:49 - INFO	| calculated.fighting:144 - 3.1 -  完成自动战斗

**Comment by moulai** [comment]
是的，我也出现了这个问题，用的三月七跑图。

**Comment by Night-stars-1** [comment]
转向函数已修复
