### ISSUE TITLE
[Bug] Traceback (most recent call last)

### ISSUE THREAD

**Issue by ZouloveGhack** [Starry-Wind/StarRailAssistant#277]
### 问题描述

当我[资源文件更新]更新完成. 时候就出现这错误 请问如何绝决
Traceback (most recent call last):
  File "C:\Users\Z\Downloads\StarRailAssistant-1.5.1\Honkai_Star_Rail.py", line 167, in <module>
    exit()
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: None

### 预期行为

不会出现红字

### 实际行为

当我更新文件后就会出下这个错误

### 截图或录屏

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/28489226/10d5d1a8-bc02-40a3-9967-e9a7925cb7c2)

### 自动锄大地脚本版本

V1.5.1

### 星穹铁道区服

国际服

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11562413/default.log)

**Comment by Night-stars-1** [comment]
更新1.5.3
