### ISSUE TITLE
[Bug] 无法启动TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by sunFlying** [Starry-Wind/StarRailAssistant#284]
### 问题描述

无法启动
日志报错
TypeError: cannot unpack non-iterable NoneType object

### 预期行为

无法启动
日志报错
TypeError: cannot unpack non-iterable NoneType object

### 实际行为

无法启动
日志报错
TypeError: cannot unpack non-iterable NoneType object

### 截图或录屏

无法启动
日志报错
TypeError: cannot unpack non-iterable NoneType object
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/16077886/8c50b2ac-5c03-406f-8be4-ece172b8f3fa)

### 自动锄大地脚本版本

StarRailAssistant-1.5.3

### 星穹铁道区服

国服

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11566518/default.log)

**Comment by Night-stars-1** [comment]
地图为空请下载地图
