### ISSUE TITLE
[Bug] temp 图片变动导致的图片缺失

### ISSUE THREAD

**Issue by misuki-39** [Starry-Wind/StarRailAssistant#291]
### 问题描述

map/map_1-1_1.json 中仍使用 "temp\\orientation_2.png", 但是 该图片在 648d0dfffc8fd26ed6ef18924a59a86570bbc988 后 没了,

PS: 使用 cp temp/pc* temp/ 能解决, 但是以后map分支能不能多一个备份分支,  这样出错了方便回退下载

### 预期行为

能选择第一星球

### 实际行为

opencv 找不到图片, 报错

### 自动锄大地脚本版本

main

### 星穹铁道区服

国服

### 日志

[1.log](https://github.com/Starry-Wind/StarRailAssistant/files/11569347/1.log)
log是空的, 不用看了

**Comment by Night-stars-1** [comment]
你可以fork，map分支并添加图片之后pr
该问题最新版不会出现，我们不对旧版本就行维护
