### ISSUE TITLE
[功能请求] 模拟器适配

### ISSUE THREAD

**Issue by MaxYu2** [Starry-Wind/StarRailAssistant#295]
### 原因

目前是前台运行，遇到像希尔这样的闪光弹角色就很难受。同时前台运行很难执行多任务，挂机摸鱼也很难受。

### 功能简述

模拟器适配，需要打包成apk格式的sra

### 功能逻辑

可以有一个悬浮窗口进行控制

### 实现参考

maa等，只要做一个分辨率就行，毕竟是模拟器，感谢大大

**Comment by Night-stars-1** [comment]
已适配模拟器
