### ISSUE TITLE
[Bug] 报错can not find model file C:\Users\gyh19\AppData\Roaming\cnstd\1.2\ppocr\ch_PP-OCRv2_det_infer.onnx

### ISSUE THREAD

**Issue by Guoyh1212** [Starry-Wind/StarRailAssistant#305]
### 问题描述

在首次运行更新模拟器运行环境时，由于代理网络中断，导致下载中断了，之后运行脚本就一直报错
[WARNING 2023-05-27 03:46:47,131 _assert_and_prepare_model_files:124] can not find model file C:\Users\gyh19\AppData\Roaming\cnstd\1.2\ppocr\ch_PP-OCRv2_det_infer.onnx
尝试过去找这个文件下载，但是没有找到，请问有没有办法初始化这个运行环境？

### 预期行为

尝试过去找这个文件下载，但是没有找到；尝试过卸载cnstd，也没办法解决该问题，请问有没有办法初始化这个运行环境？

### 实际行为

现在可以更新，但是不管是PC平台还是模拟器平台运行脚本都会报这个错误

### 截图或录屏

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/93355016/265751cc-e005-46bf-b5c3-b186a383708b)

### 自动锄大地脚本版本

1.5.4

### 星穹铁道区服

国服

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11579577/default.log)

**Comment by Night-stars-1** [comment]
删除`C:\Users\gyh19\AppData\Roaming\cnstd\1.2\ppocr\`下的`ch_PP-OCRv2_det_infer.onnx`文件，重新运行脚本
