### ISSUE TITLE
3A平台导包错误ERROR: Polygon3-3.0.9-cp311-cp311-win_amd64.whl is not a supported wheel on this platform[Bug] 

### ISSUE THREAD

**Issue by a871581661** [Starry-Wind/StarRailAssistant#311]
### 问题描述

pip install -r requirements.txt
ERROR: Polygon3-3.0.9-cp311-cp311-win_amd64.whl is not a supported wheel on this platform
cpu:amd 2600
显卡: rx580

### 预期行为

.

### 实际行为

.

### 截图或录屏

。

### 自动锄大地脚本版本

2.7test

### 星穹铁道区服

国服

### 日志

。

**Comment by Night-stars-1** [comment]
python3.11

**Comment by dConstantineb** [comment]
将requirement.txt中whl\Polygon3-3.0.9.1-cp311-cp311-win_amd64.whl改为whl\Polygon3-3.0.9.1-cp310-cp310-win_amd64.whl，同时准备相应依赖包即可

**Comment by DLmaster361** [comment]
请按照教程，安装3.11版本的Python，最新版本3.12不支持
