### ISSUE TITLE
[Bug] 运行的时候，直接闪退脚本。

### ISSUE THREAD

**Issue by iceNo9** [Starry-Wind/StarRailAssistant#312]
### 问题描述

脚本运行过程，人没动了，我看了下，bat的那个窗口没了

### 预期行为

正常锄完大地

### 实际行为

bat脚本没了

### 自动锄大地脚本版本

v1.5.5

### 星穹铁道区服

国服

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11581635/default.log)

**Comment by Night-stars-1** [comment]
我们没有提供bat启动方式
