### ISSUE TITLE
[Bug] 迴星港不点飞星小筑

### ISSUE THREAD

**Issue by fanshu-520** [Starry-Wind/StarRailAssistant#316]
### 问题描述

迴星港不点飞星小筑

### 预期行为

正常应该点击飞星小筑

### 实际行为

迴星港不点飞星小筑

### 截图或录屏

![图片](https://github.com/Starry-Wind/StarRailAssistant/assets/79776977/f772ccf4-0dec-4927-a50d-d5637b9d15a2)

### 自动锄大地脚本版本

1.5.5

### 星穹铁道区服

国服

### 日志

01:09:51 - DEBUG	| map.read_maps:95 - 20230528005858/20230527234756/20230527234756 -  ['map_1-1_1.json', 'map_1-2_1.json', 'map_1-2_2.json', 'map_1-2_3.json', 'map_1-2_4.json', 'map_1-3_1.json', 'map_1-3_2.json', 'map_1-3_3.json', 'map_1-3_4.json', 'map_2-1_1.json', 'map_2-1_2.json', 'map_2-2_1.json', 'map_2-2_2.json', 'map_2-3_1.json', 'map_2-3_2.json', 'map_2-3_3.json', 'map_2-3_4.json', 'map_2-3_5.json', 'map_2-4_1.json', 'map_2-4_2.json', 'map_2-5_1.json', 'map_2-5_2.json', 'map_2-5_3.json', 'map_2-5_4.json', 'map_2-6_1.json', 'map_2-6_2.json', 'map_2-7_1.json', 'map_2-7_2.json', 'map_2-7_3.json', 'map_3-1_1.json', 'map_3-1_2.json', 'map_3-1_3.json', 'map_3-1_4.json', 'map_3-2_1.json', 'map_3-2_2.json', 'map_3-2_3.json', 'map_3-2_4.json', 'map_3-2_5.json', 'map_3-3_1.json', 'map_3-3_2.json', 'map_3-3_3.json', 'map_3-3_4.json', 'map_3-4_1.json', 'map_3-4_2.json', 'map_3-4_3.json', 'map_3-4_4.json', 'map_3-4_5.json', 'map_3-4_6.json']
01:09:51 - DEBUG	| map.read_maps:96 - 20230528005858/20230527234756/20230527234756 -  {'1': {'1_1': '基座舱段-1', '2_1': '收容舱段-1', '2_2': '收容舱段-2', '2_3': '收容舱段-2', '2_4': '收容舱段-3', '3_1': '支援舱段-1', '3_2': '支援舱段-2', '3_3': '支援舱段-3', '3_4': '支援舱段-4'}, '2': {'1_1': '城郊雪原-1', '1_2': '城郊雪原-2', '2_1': '边缘道路-1', '2_2': '边缘道路-2', '3_1': '残响回廊-1', '3_2': '残响回廊-2', '3_3': '残响回廊-3', '3_4': '残响回廊-4', '3_5': '残响回廊-5', '4_1': '永冬岭-1', '4_2': '永冬岭-2', '5_1': '大矿区-1', '5_2': '大矿区-2', '5_3': '大矿区-3', '5_4': '大矿区-4', '6_1': '铆钉镇-1', '6_2': '铆钉镇-2', '7_1': '机器聚落-1', '7_2': '机器聚落-2', '7_3': '机器聚落-3'}, '3': {'1_1': '流云渡-1', '1_2': '流云渡-2', '1_3': '流云渡-3', '1_4': '流云渡-4', '2_1': '迥星港-1', '2_2': '迥星港-2', '2_3': '迥星港-3', '2_4': '迥星港-4', '2_5': '迥星港-5', '3_1': '太卜司-1', '3_2': '太卜司-2', '3_3': '太卜司-3', '3_4': '太卜司-4', '4_1': '工造司-1', '4_2': '工造司-2', '4_3': '工造司-3', '4_4': '工造司-4', '4_5': '工造司-5', '4_6': '工造司-6'}}
01:09:55 - INFO	| requests.webhook_and_log:80 - 20230528005858/20230527234756/20230527234756 -  开始[0;34;40m迥星港-1[0m锄地
01:09:55 - INFO	| map.auto_map:109 - 20230528005858/20230527234756/20230527234756 -  该路线导航作者：[0;31;40m雪见璃[0m
01:09:55 - INFO	| map.auto_map:110 - 20230528005858/20230527234756/20230527234756 -  感谢每一位无私奉献的作者
01:09:55 - DEBUG	| map.auto_map:113 - 20230528005858/20230527234756/20230527234756 -  map
01:09:55 - DEBUG	| calculated.img_click:156 - 20230528005858/20230527234756/20230527234756 -  (132, 82)
01:09:56 - DEBUG	| calculated.part_ocr:573 - 20230528005858/20230527234756/20230527234756 -  {'导航': (103, 25)}
01:09:56 - INFO	| calculated.open_map:678 - 20230528005858/20230527234756/20230527234756 -  进入地图
01:09:56 - DEBUG	| calculated.img_click:156 - 20230528005858/20230527234756/20230527234756 -  (366, 660)
01:09:56 - DEBUG	| calculated.img_click:156 - 20230528005858/20230527234756/20230527234756 -  (366, 660)
01:09:56 - DEBUG	| calculated.img_click:156 - 20230528005858/20230527234756/20230527234756 -  (366, 660)
01:09:56 - DEBUG	| calculated.img_click:156 - 20230528005858/20230527234756/20230527234756 -  (366, 660)
01:09:56 - DEBUG	| calculated.img_click:156 - 20230528005858/20230527234756/20230527234756 -  (366, 660)
01:09:56 - DEBUG	| map.auto_map:113 - 20230528005858/20230527234756/20230527234756 -  temp\orientation_1.jpg
01:09:58 - DEBUG	| calculated.ocr_pos:554 - 20230528005858/20230527234756/20230527234756 -  {'9': array([[         47,          19],
       [         75,          19],
       [         75,          53],
       [         47,          53]], dtype=float32), '号航': array([[         73,          17],
       [        118,           8],
       [        123,          32],
       [         79,          42]], dtype=float32), '仙舟「罗浮」': array([[         78,          35],
       [        200,          35],
       [        200,          63],
       [         78,          63]], dtype=float32), '物28/180 +': array([[       1023,          21],
       [       1155,          21],
       [       1155,          50],
       [       1023,          50]], dtype=float32), '大': array([[       1215,          13],
       [       1251,          19],
       [       1245,          56],
       [       1209,          50]], dtype=float32), '星轨航图': array([[       1005,          84],
       [       1093,          84],
       [       1093,         111],
       [       1005,         111]], dtype=float32), 'n': array([[       1225,          82],
       [       1239,          96],
       [       1226,         108],
       [       1212,          95]], dtype=float32), '观景车厢': array([[        903,         164],
       [       1025,         164],
       [       1025,         191],
       [        903,         191]], dtype=float32), '大星槎海中枢': array([[        900,         244],
       [       1044,         241],
       [       1045,         270],
       [        901,         273]], dtype=float32), '长乐天': array([[        897,         321],
       [       1000,         321],
       [       1000,         357],
       [        897,         357]], dtype=float32), '+流云渡': array([[        898,         403],
       [        998,         403],
       [        998,         432],
       [        898,         432]], dtype=float32), '·迥星港': array([[        900,         484],
       [        998,         484],
       [        998,         513],
       [        900,         513]], dtype=float32), '·太卜司': array([[        900,         564],
       [       1000,         564],
       [       1000,         593],
       [        900,         593]], dtype=float32), 'X': array([[        673,         649],
       [        683,         656],
       [        678,         665],
       [        667,         658]], dtype=float32), '工造司': array([[        902,         643],
       [        998,         643],
       [        998,         672],
       [        902,         672]], dtype=float32), 'UID:10222836': array([[         27,         686],
       [        137,         686],
       [        137,         709],
       [         27,         709]], dtype=float32)}
01:09:59 - DEBUG	| map.auto_map:113 - 20230528005858/20230527234756/20230527234756 -  temp\orientation_4.png
01:10:01 - DEBUG	| map.auto_map:113 - 20230528005858/20230527234756/20230527234756 -  temp\map_3-2.png
01:10:04 - DEBUG	| calculated.part_ocr:573 - 20230528005858/20230527234756/20230527234756 -  {'观景车厢': (972, 177), '星槎海中': (974, 257), '长乐天': (962, 337), '流云渡': (961, 417), '迥星港': (961, 497), '太卜司': (961, 578), '工造司': (962, 658)}
01:10:04 - DEBUG	| calculated.appoint_click:89 - 20230528005858/20230527234756/20230527234756 -  (961, 497)
01:10:04 - DEBUG	| calculated.appoint_click:89 - 20230528005858/20230527234756/20230527234756 -  (961, 497)
01:10:05 - DEBUG	| map.auto_map:113 - 20230528005858/20230527234756/20230527234756 -  temp\map_3-2_point_1.png
01:10:07 - DEBUG	| map.auto_map:113 - 20230528005858/20230527234756/20230527234756 -  temp\map_3-2_point_2.png

**Comment by fanshu-520** [comment]
fix:将游戏画质调整到低 而不是最低即可

**Comment by Serein1202** [comment]
谢谢，这个问题困扰了我很久
