### ISSUE TITLE
[Bug] 切换地图锄地程序中止

### ISSUE THREAD

**Issue by wenbuer** [Starry-Wind/StarRailAssistant#318]
### 问题描述

切换地图锄地程序中止，同一地图内小阶段也是一样
日志内容如下

09:30:01 - INFO	| map.auto_map:123 - 20230528005858/20230527234756/20230527234756 -  地图加载完毕，加载时间为 0.04936647415161133 秒
09:30:03 - INFO	| map.start_map:54 - 20230528005858/20230527234756/20230527234756 -  开始寻路
09:30:03 - INFO	| map.start_map:56 - 20230528005858/20230527234756/20230527234756 -  执行map_1-3_2文件:1/3 {'s': 5.428497314453125}
09:30:08 - INFO	| map.start_map:56 - 20230528005858/20230527234756/20230527234756 -  执行map_1-3_2文件:2/3 {'w': 0.5379721641540527}
09:30:09 - INFO	| map.start_map:56 - 20230528005858/20230527234756/20230527234756 -  执行map_1-3_2文件:3/3 {'f': 0.6}
09:30:11 - INFO	| requests.webhook_and_log:80 - 20230528005858/20230527234756/20230527234756 -  开始[0;34;40m支援舱段-3[0m锄地
09:30:11 - INFO	| map.auto_map:109 - 20230528005858/20230527234756/20230527234756 -  该路线导航作者：[0;31;40mStarry-Wind,小明[0m
09:30:11 - INFO	| map.auto_map:110 - 20230528005858/20230527234756/20230527234756 -  感谢每一位无私奉献的作者
09:30:14 - INFO	| calculated.wait_join:643 - 20230528005858/20230527234756/20230527234756 -  已进入地图
09:30:14 - INFO	| map.auto_map:123 - 20230528005858/20230527234756/20230527234756 -  地图加载完毕，加载时间为 0.05944633483886719 秒
09:30:16 - INFO	| map.start_map:54 - 20230528005858/20230527234756/20230527234756 -  开始寻路
09:30:16 - INFO	| map.start_map:56 - 20230528005858/20230527234756/20230527234756 -  执行map_1-3_3文件:1/8 {'w': 0.8554380893707275}
09:30:17 - INFO	| map.start_map:56 - 20230528005858/20230527234756/20230527234756 -  执行map_1-3_3文件:2/8 {'d': 5.253693923950196}
09:30:22 - INFO	| map.start_map:56 - 20230528005858/20230527234756/20230527234756 -  执行map_1-3_3文件:3/8 {'fighting': 1}
09:30:22 - INFO	| calculated.fighting:343 - 20230528005858/20230527234756/20230527234756 -  识别中
09:30:29 - INFO	| calculated.fighting:384 - 20230528005858/20230527234756/20230527234756 -  跳过开启自动战斗（沿用设置）
09:30:34 - DEBUG	| calculated.fighting:395 - 20230528005858/20230527234756/20230527234756 -  (2096.5, 205.0)
09:30:34 - INFO	| calculated.fighting:396 - 20230528005858/20230527234756/20230527234756 -  完成自动战斗
09:30:37 - INFO	| map.start_map:56 - 20230528005858/20230527234756/20230527234756 -  执行map_1-3_3文件:4/8 {'a': 11.320342826843262}
09:30:48 - INFO	| map.start_map:56 - 20230528005858/20230527234756/20230527234756 -  执行map_1-3_3文件:5/8 {'w': 3.656429147720337}
09:30:52 - INFO	| map.start_map:56 - 20230528005858/20230527234756/20230527234756 -  执行map_1-3_3文件:6/8 {'fighting': 1}
09:30:52 - INFO	| calculated.fighting:343 - 20230528005858/20230527234756/20230527234756 -  识别中
09:30:53 - INFO	| calculated.fighting:357 - 20230528005858/20230527234756/20230527234756 -  识别到疑问或是警告,等待怪物开战
09:31:02 - INFO	| calculated.fighting:384 - 20230528005858/20230527234756/20230527234756 -  跳过开启自动战斗（沿用设置）
09:31:07 - DEBUG	| calculated.fighting:395 - 20230528005858/20230527234756/20230527234756 -  (2195.5, 482.0)
09:31:07 - INFO	| calculated.fighting:396 - 20230528005858/20230527234756/20230527234756 -  完成自动战斗
09:31:10 - INFO	| map.start_map:56 - 20230528005858/20230527234756/20230527234756 -  执行map_1-3_3文件:7/8 {'d': 0.856429147720337}
09:31:11 - INFO	| map.start_map:56 - 20230528005858/20230527234756/20230527234756 -  执行map_1-3_3文件:8/8 {'fighting': 2}
09:31:12 - INFO	| requests.webhook_and_log:80 - 20230528005858/20230527234756/20230527234756 -  开始[0;34;40m支援舱段-4[0m锄地
09:31:12 - INFO	| map.auto_map:109 - 20230528005858/20230527234756/20230527234756 -  该路线导航作者：[0;31;40mStarry-Wind,小明[0m
09:31:12 - INFO	| map.auto_map:110 - 20230528005858/20230527234756/20230527234756 -  感谢每一位无私奉献的作者
09:31:12 - DEBUG	| map.auto_map:113 - 20230528005858/20230527234756/20230527234756 -  map

此处之后程序未退出，但不再执行

### 预期行为

切换地图之后，calculated.part_ocr方法开始执行
如昨天日志流程

15:46:35 - INFO	| Honkai_Star_Rail.main:75 - 20230527145152/20230527020715/20230527020715 -  开始运行，请勿移动鼠标和键盘
15:46:35 - INFO	| Honkai_Star_Rail.main:76 - 20230527145152/20230527020715/20230527020715 -  若脚本运行无反应,请使用管理员权限运行
15:46:35 - INFO	| requests.webhook_and_log:80 - 20230527145152/20230527020715/20230527020715 -  开始[0;34;40m城郊雪原-1[0m锄地
15:46:35 - INFO	| map.auto_map:104 - 20230527145152/20230527020715/20230527020715 -  该路线导航作者：[0;31;40mStarry-Wind,小明[0m
15:46:35 - INFO	| map.auto_map:105 - 20230527145152/20230527020715/20230527020715 -  感谢每一位无私奉献的作者
15:46:35 - DEBUG	| map.auto_map:108 - 20230527145152/20230527020715/20230527020715 -  map
15:46:36 - DEBUG	| calculated.part_ocr:551 - 20230527145152/20230527020715/20230527020715 -  {}
15:46:38 - DEBUG	| calculated.part_ocr:551 - 20230527145152/20230527020715/20230527020715 -  {'导加': (125, 87)}
15:46:40 - DEBUG	| calculated.part_ocr:551 - 20230527145152/20230527020715/20230527020715 -  {}
15:46:41 - DEBUG	| calculated.part_ocr:551 - 20230527145152/20230527020715/20230527020715 -  {'导加': (125, 87)}
15:46:43 - DEBUG	| calculated.part_ocr:551 - 20230527145152/20230527020715/20230527020715 -  {}
15:46:44 - DEBUG	| calculated.part_ocr:551 - 20230527145152/20230527020715/20230527020715 -  {'导加': (125, 87)}
15:46:46 - DEBUG	| calculated.part_ocr:551 - 20230527145152/20230527020715/20230527020715 -  {}
15:46:46 - INFO	| calculated.open_map:661 - 20230527145152/20230527020715/20230527020715 -  识别超时
15:47:37 - DEBUG	| map.map_init:38 - 20230527145152/20230527020715/20230527020715 -  (633.5, 1019.0)

### 实际行为

日志输入key值map之后卡死，执行中断，程序未退出

### 自动锄大地脚本版本

20230528005858/20230527234756/20230527234756

### 星穹铁道区服

国服

### 日志

[日志文件-0528-1.log](https://github.com/Starry-Wind/StarRailAssistant/files/11583416/-0528-1.log)
[日志文件-0528-2.log](https://github.com/Starry-Wind/StarRailAssistant/files/11583417/-0528-2.log)

**Comment by d170798091** [comment]
現在感覺戰鬥完後 馬上就會接著動作 會讓後續進行失敗

**Comment by hhzxxx** [comment]
发现一个现象是，角色施放大招后就检测到了自动战斗完成，然后开始执行后续操作导致卡住。
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/62325706/4f8cc91b-72ef-47dd-9e82-9c391815e92d)

**Comment by Starry-Wind** [comment]
> 发现一个现象是，角色施放大招后就检测到了自动战斗完成，然后开始执行后续操作导致卡住。 ![图像](https://user-images.githubusercontent.com/62325706/241482603-4f8cc91b-72ef-47dd-9e82-9c391815e92d.png)

pc还是模拟器？

**Comment by Starry-Wind** [comment]
新版本已修复
