### ISSUE TITLE
[Bug] 问题 模拟器？ 但我是电脑 和 exceptions.__init__:19 - 0/0/0 - 请重新运行1.5.5ver

### ISSUE THREAD

**Issue by ZouloveGhack** [Starry-Wind/StarRailAssistant#323]
### 问题描述

我使用电脑运行但是选择更新文件时弹出选择模拟器问题是我用的是电脑没有下载模拟器我该怎么办
随便选择模拟器后我点全部更新就看到* server not running *

### 预期行为

更新地图或者有主机（PC）选项
更新地图时出现exceptions.__init__:19 - 0/0/0 - 请重新运行

### 实际行为

都是模拟器我选那个
...

### 截图或录屏

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/28489226/f4d31c38-ba67-4310-8350-30b6c370b858)
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/28489226/2986c38f-3bd8-4a9a-b36f-9d122d644d73)

### 自动锄大地脚本版本

1.5.5

### 星穹铁道区服

国际服

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11584530/default.log)

**Comment by Night-stars-1** [comment]
emm，这个是配置模拟器的运行平台，他不影响你选择PC运行
