### ISSUE TITLE
[Bug] [资源文件更新]utils\config.py校验失败, 程序退出

### ISSUE THREAD

**Issue by d170798091** [Starry-Wind/StarRailAssistant#327]
### 问题描述

[资源文件更新]utils\config.py校验失败, 程序退出

### 预期行为

正常更新

### 实际行为

[资源文件更新]utils\config.py校验失败, 程序退出

### 自动锄大地脚本版本

last ver

### 星穹铁道区服

国际服

### 日志

00:04:47 - INFO	| update_file.update_file:133 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在检查远程版本是否有更新...
00:04:47 - INFO	| update_file.update_file:151 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]获取远程版本成功: 20230528202637
00:04:47 - INFO	| update_file.update_file:156 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]本地版本与远程版本不符，开始更新资源文件->https://github.com/Starry-Wind/StarRailAssistant/archive/refs/heads/main.zip
00:04:48 - INFO	| update_file.update_file:160 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]下载更新包成功, 正在覆盖本地文件: 20230528144104 -> 20230528202637
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/ISSUE_TEMPLATE/
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/ISSUE_TEMPLATE/bug_report.yml
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/ISSUE_TEMPLATE/bug_report_en.yml
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/ISSUE_TEMPLATE/config.yml
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/ISSUE_TEMPLATE/feature_request.yml
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/ISSUE_TEMPLATE/feature_request_en.yml
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/ISSUE_TEMPLATE/route_bug.yml
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/ISSUE_TEMPLATE/route_bug_en.yml
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/release.yml
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/workflows/
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/workflows/auto-merge.yml
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/workflows/codeql.yml
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/workflows/dependency-review.yml
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/workflows/update_map.yml
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/workflows/update_requirements.yml
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.github/workflows/upload-to-release.yml
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/.gitignore
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/Honkai_Star_Rail.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/LICENSE
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/README.md
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/README_CHT.md
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/get_width.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/map_res_list.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/requirements.txt
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/screencast.png
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/star_list.json
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/utils/
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/utils/adb.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/utils/calculated.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/utils/config.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/utils/cv_tools.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/utils/cv_tracker.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/utils/exceptions.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/utils/log.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/utils/map.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/utils/record_v7.2.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/utils/requests.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/utils/simulated_universe.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/utils/update_file.py
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/version.json
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/whl/
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/whl/Polygon3-3.0.9-cp311-cp311-win_amd64.whl
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/whl/Polygon3-3.0.9.1-cp310-cp310-win_amd64.whl
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/whl/cnocr-2.2.2.3-py3-none-any.whl
00:04:48 - DEBUG	| update_file.unzip:54 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在提取StarRailAssistant-main/whl/cnstd-1.2.2-py3-none-any.whl
00:04:48 - INFO	| update_file.update_file:178 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]正在校验资源文件
00:04:49 - DEBUG	| update_file.verify_file_hash:43 - 20230528144104/20230528163825/20230528163825 -  a2d373ed73e25024c16633e41d397c44
00:04:49 - DEBUG	| update_file.verify_file_hash:43 - 20230528144104/20230528163825/20230528163825 -  05e4b278d56fe0737b578e54f78a4756
00:04:49 - DEBUG	| update_file.verify_file_hash:43 - 20230528144104/20230528163825/20230528163825 -  9cb0a26a887005e0ac5d1351e34e6610
00:04:49 - DEBUG	| update_file.verify_file_hash:43 - 20230528144104/20230528163825/20230528163825 -  73fd6ced86a53698cea6e00f2ecf2bbc
00:04:49 - DEBUG	| update_file.verify_file_hash:43 - 20230528144104/20230528163825/20230528163825 -  164c5db97e05563b37fc8ef38be1e47d
00:04:49 - DEBUG	| update_file.verify_file_hash:43 - 20230528144104/20230528163825/20230528163825 -  4b70e6f84073317eb1f1cb17e4e2509a
00:04:49 - DEBUG	| update_file.verify_file_hash:43 - 20230528144104/20230528163825/20230528163825 -  6ab23531dc5dd3d1d4cda420733b3c4e
00:04:49 - DEBUG	| update_file.verify_file_hash:43 - 20230528144104/20230528163825/20230528163825 -  b540bcf1f23e64c1443a23c0d382db99
00:04:49 - DEBUG	| update_file.verify_file_hash:43 - 20230528144104/20230528163825/20230528163825 -  5d95e2a8485cff370478c39b104b708b
00:04:49 - ERROR	| exceptions.__init__:19 - 20230528144104/20230528163825/20230528163825 -  [资源文件更新]utils\config.py校验失败, 程序退出
00:04:49 - DEBUG	| exceptions.__init__:20 - 20230528144104/20230528163825/20230528163825 -  NoneType: None

**Comment by Night-stars-1** [comment]
意外事故，已修复
