### ISSUE TITLE
[Bug] PC 鋤大地無限loop M鍵開地圖

### ISSUE THREAD

**Issue by d170798091** [Starry-Wind/StarRailAssistant#330]
### 问题描述

PC 鋤大地無限loop M鍵開地圖

### 预期行为

開完地圖傳送指定區域

### 实际行为

無限loop M鍵開地圖

### 自动锄大地脚本版本

last ver

### 星穹铁道区服

国际服

### 日志

14:53:57 - DEBUG	| map.read_maps:97 - 20230529135043/20230528163825/20230528163825 -  {'1': {'1_1': '基座舱段-1', '2_1': '收容舱段-1', '2_2': '收容舱段-2', '2_3': '收容舱段-2', '2_4': '收容舱段-3', '3_1': '支援舱段-1', '3_2': '支援舱段-2', '3_3': '支援舱段-3', '3_4': '支援舱段-4'}, '2': {'1_1': '城郊雪原-1', '1_2': '城郊雪原-2', '2_1': '边缘道路-1', '2_2': '边缘道路-2', '3_1': '残响回廊-1', '3_2': '残响回廊-2', '3_3': '残响回廊-3', '3_4': '残响回廊-4', '3_5': '残响回廊-5', '4_1': '永冬岭-1', '4_2': '永冬岭-2', '5_1': '大矿区-1', '5_2': '大矿区-2', '5_3': '大矿区-3', '5_4': '大矿区-4', '6_1': '铆钉镇-1', '6_2': '铆钉镇-2', '7_1': '机器聚落-1', '7_2': '机器聚落-2', '7_3': '机器聚落-3'}, '3': {'1_1': '流云渡-1', '1_2': '流云渡-2', '1_3': '流云渡-3', '1_4': '流云渡-4', '2_1': '迥星港-1', '2_2': '迥星港-2', '2_3': '迥星港-3', '2_4': '迥星港-4', '2_5': '迥星港-5', '3_1': '太卜司-1', '3_2': '太卜司-2', '3_3': '太卜司-3', '3_4': '太卜司-4', '4_1': '工造司-1', '4_2': '工造司-2', '4_3': '工造司-3', '4_4': '工造司-4', '4_5': '工造司-5', '4_6': '工造司-6'}}
14:53:58 - INFO	| Honkai_Star_Rail.main:73 - 20230529135043/20230528163825/20230528163825 -  脚本将自动切换至游戏窗口，请保持游戏窗口激活
14:53:59 - INFO	| get_width.get_width:52 - 
14:56:00 - INFO	| get_width.get_width:52 - 20230529135043/20230528163825/20230528163825 -  Real resolution: 1920 x 1080 x 1.0
14:56:00 - INFO	| Honkai_Star_Rail.main:78 - 20230529135043/20230528163825/20230528163825 -  开始运行，请勿移动鼠标和键盘
14:56:00 - INFO	| Honkai_Star_Rail.main:79 - 20230529135043/20230528163825/20230528163825 -  若脚本运行无反应,请使用管理员权限运行
14:56:00 - INFO	|

**Comment by Night-stars-1** [comment]
已修复

**Comment by lx1169732264** [comment]
> 已修复

我用的main分支最新的代码,这个问题还存在

**Comment by Night-stars-1** [comment]
> > 已修复
> 
> 我用的main分支最新的代码,这个问题还存在

是的因为坐标的错误纠正，目前这个因为应该是修复了，这个issues我重新打开，麻烦之后反馈一下是否修复了

**Comment by zty1017** [comment]
> 

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/57761557/9fae4cbb-68d1-4c93-b2de-0984774168a8)
早上更新脚本如何试了下，还是会无限循环打开关闭大地图
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/57761557/864b235e-a5a7-4f56-a3ed-ab3af8ac9cd2)

**Comment by lnnh** [comment]
同上，这几天更新几次都是无限循环打开关闭地图

**Comment by skycon8** [comment]
更新了无限按M循环问题还在

![m](https://github.com/Starry-Wind/StarRailAssistant/assets/104609415/4406b7a4-142b-43d6-b951-483f4149ada1)
![m2](https://github.com/Starry-Wind/StarRailAssistant/assets/104609415/1da446ba-8a9a-48b6-bbae-6a2fb9302a15)

**Comment by skycon8** [comment]
谢谢，可以执行了。感激

**Comment by Night-stars-1** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/57761557/241822571-9fae4cbb-68d1-4c93-b2de-0984774168a8.png) 早上更新脚本如何试了下，还是会无限循环打开关闭大地图 ![image](https://user-images.githubusercontent.com/57761557/241822714-864b235e-a5a7-4f56-a3ed-ab3af8ac9cd2.png)

你好最新版还会出现这个问题吗？

**Comment by zty1017** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/57761557/241822571-9fae4cbb-68d1-4c93-b2de-0984774168a8.png) 早上更新脚本如何试了下，还是会无限循环打开关闭大地图 ![image](https://user-images.githubusercontent.com/57761557/241822714-864b235e-a5a7-4f56-a3ed-ab3af8ac9cd2.png)
> 
> 你好最新版还会出现这个问题吗？

刚试了更新了最新版能正常使用了
