### ISSUE TITLE
[Bug] 地图模拟按键定位错误

### ISSUE THREAD

**Issue by nyano** [Starry-Wind/StarRailAssistant#338]
### 问题描述

版本：1.5.5（今天全部更新到最新）
显示器：3屏，一个1080P，另外2台4k 150%DPI，运行在 4k150%DPI显示器上
上个版本一切正常，仅存在于今天的版本

1.似乎与steam++冲突，在其中打开github代理后，弹SSL错误 系统找不到指定的路径。
运行脚本即弹出。日志中的httpx.ConnectTimeout是关闭steam++后发生的，应该是跟github连接失败，包括在与选择代理测速时部分发生。
但是这不重要（前几个版本没遇到过）

2.在窗口化1080P下[运行在4k 150%显示器中]
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/5079651/93406ec0-bfc2-4792-b5b7-80eecdeb5ca9)
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/5079651/13e51c07-b94b-485e-883c-1c488a240246)
在进入地图时，在缩放地图状态，鼠标点击的是上方60-100px像素区域。点击星轨航图时，选中的是上方开拓力补充按钮60px？
似乎没有屏蔽掉窗口栏的px？
脚本中显示窗口信息为：Real resolution: 1295 x 757 x 1.5 

3.在4k显示器中使用1080P全屏化 
或窗口化的情况下使用最新的main分支脚本
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/5079651/77c3aa01-398c-4487-ba29-60f9b4c01547)

Real resolution: 2560 x 1440 x 1.5

会不断弹出、关闭地图界面，不断开关，无其他动作

### 预期行为

1

### 实际行为

1

### 自动锄大地脚本版本

1.5.5 和main

### 星穹铁道区服

国服

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11591513/default.log)

**Comment by Night-stars-1** [comment]
已修复
