### ISSUE TITLE
[功能请求] 更新脚本时允许选择使用git来进行更新

### ISSUE THREAD

**Issue by guch8017** [Starry-Wind/StarRailAssistant#351]
### 原因

目前脚本自动更新是采用直接覆盖的方式进行的，和git版本管理之间有冲突。

### 功能简述

在系统安装了git且是使用`git clone`或者`git pull`情况下获取软件代码的情况下采用`git pull`的方式来更新而不是直接进行解压覆盖操作。

### 功能逻辑

可在配置文件中添加对应选项，或自动检测环境（如`os.system('git pull')`返回值为0即为更新成功）

**Comment by Night-stars-1** [comment]
我这边是没有冲突的，两个一起用好好的
