### ISSUE TITLE
[Bug] ocr识别问题

### ISSUE THREAD

**Issue by Gaoway** [Starry-Wind/StarRailAssistant#354]
### 问题描述

前面有issue提到不停m键打开map，可能的原因是ocr识别问题。
有可能是分辨率1616 x 939 问题, 但是这个分辨率差别不大了

### 预期行为

预期识别为
```
导航
```

### 实际行为

我的界面大小：Real resolution: 1616 x 939 x 1.0
识别结果：
```
{'导机几': (239, 137), '空间站「黑塔': (287, 159)}
{'白I': (337, 161)}
{'导机几': (239, 137), '空间站「黑塔': (287, 159)}
{'白I': (337, 161)}
```
在
``` python
if "导航" in map_status:
    log.info("进入地图")
    break
if time.time() - start_time > 10:
    log.info("识别超时")
    break
```
出现重复

### 自动锄大地脚本版本

2.7

### 星穹铁道区服

国服

### 日志

16:31:29 - DEBUG	| calculated.part_ocr:598 - 20230530132155/20230528163825/20230528163825 -  {'导机几': (239, 137), '空间站「黑塔': (287, 159)}
16:31:30 - DEBUG	| calculated.part_ocr:598 - 20230530132155/20230528163825/20230528163825 -  {'白I': (337, 161)}
16:31:32 - DEBUG	| calculated.part_ocr:598 - 20230530132155/20230528163825/20230528163825 -  {'导机几': (239, 137), '空间站「黑塔': (287, 159)}
16:31:33 - DEBUG	| calculated.part_ocr:598 - 20230530132155/20230528163825/20230528163825 -  {'白I': (337, 161)}
16:31:34 - DEBUG	| calculated.part_ocr:598 - 20230530132155/20230528163825/20230528163825 -  {'导机几': (239, 137), '空间站「黑塔': (287, 159)}
16:31:36 - DEBUG	| calculated.part_ocr:598 - 20230530132155/20230528163825/20230528163825 -  {'白I': (337, 161)}
16:31:37 - DEBUG	| calculated.part_ocr:598 - 20230530132155/20230528163825/20230528163825 -  {'导机几': (239, 137), '空间站「黑塔': (287, 159)}
16:31:39 - DEBUG	| calculated.part_ocr:598 - 20230530132155/20230528163825/20230528163825 -  {'白I': (337, 161)}
16:31:40 - DEBUG	| calculated.part_ocr:598 - 20230530132155/20230528163825/20230528163825 -  {'导机几': (239, 137), '空间站「黑塔': (287, 159)}

**Comment by Gaoway** [comment]
1. 建议这个部分改成
```
if "导" in map_status:
    log.info("进入地图")
    break
```

**Comment by Night-stars-1** [comment]
感谢反馈，我的电脑上这个是100%正确的所以我没注意，我改成模糊匹配吧
