### ISSUE TITLE
[Bug] 更新后运行显示no module named "flet"

### ISSUE THREAD

**Issue by AquaDeer10** [Starry-Wind/StarRailAssistant#371]
### 问题描述

更新后运行显示no module named "flet"
定位文件为
utils/requests.py line 11

应该是requirements.txt中误将flet写为了flat

### 预期行为

正常运行

### 实际行为

显示no module named "flet"

### 自动锄大地脚本版本

2.7_test

### 星穹铁道区服

国服

### 日志

no module named "flet"

**Comment by Serein1202** [comment]
不是写错了，是少写了。在requirements.txt里面加一个flet就可以正常运行了

**Comment by Night-stars-1** [comment]
> 不是写错了，是少写了。在requirements.txt里面加一个flet就可以正常运行了

是的
