### ISSUE TITLE
[Bug] start.exe 报病毒 检测（Sysmon）

### ISSUE THREAD

**Issue by ZouloveGhack** [Starry-Wind/StarRailAssistant#372]
### 问题描述

start.exe 报病毒 木马   可以修复下吗 这让我很不放心 
Matches rule CLOP Ransomware detection (Sysmon) by Ariel Millahuel at SOC Prime Threat Detection Marketplace
不是不相信但至少让我们玩的安心些

### 预期行为

没有病毒正常运行

### 实际行为

打开软件报病毒

### 截图或录屏

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/28489226/61526210-4068-4680-8dbe-8c1039b4e5b0)
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/28489226/00eca4d0-581b-4e49-87e3-58dbcb4b8fcc)

### 自动锄大地脚本版本

1.5.6

### 星穹铁道区服

国际服

### 日志

no log

**Comment by Night-stars-1** [comment]
这个exe是bat转换而来似乎调用python不符合Matches rule
并且程序会释放bat来执行这个行为会被判定为危险操作

**Comment by Night-stars-1** [comment]
我用c++重新编写了启动程序，现在不会报危险行为了
但仍有6家把文件标记为恶意程序
<img width="1088" alt="image" src="https://github.com/Starry-Wind/StarRailAssistant/assets/99261160/44aadbff-1333-4167-9152-6761e438d685">
