### ISSUE TITLE
[Bug] "System cannot find the path specified." Error

### ISSUE THREAD

**Issue by dododon22** [Starry-Wind/StarRailAssistant#374]
### Problem Description

Regardless of options I choose, I am getting the error, "System cannot find the path specified." Is it my OS not being Chinese?

### expected behavior

Assistant should run

### actual behavior

Error

### screenshot or screen recording

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/135112469/1d95b780-db57-429a-9d9e-9afa0884c6f5)

### Honkai-Star-Rail version

Current

### Honkai Star Server

Global

### log

04:57:12 - INFO	| config.init_config_file:66 - 0/0/0 -  配置初始化
04:57:34 - DEBUG	| map.read_maps:96 - 0/0/0 -  []
04:57:34 - DEBUG	| map.read_maps:97 - 0/0/0 -  {}
04:57:36 - ERROR	| exceptions.__init__:19 - 0/0/0 -  你没下载地图，拿什么选？
04:57:36 - DEBUG	| exceptions.__init__:20 - 0/0/0 -  NoneType: None

04:57:47 - DEBUG	| map.read_maps:96 - 0/0/0 -  []
04:57:47 - DEBUG	| map.read_maps:97 - 0/0/0 -  {}
04:57:58 - DEBUG	| map.read_maps:96 - 0/0/0 -  []
04:57:58 - DEBUG	| map.read_maps:97 - 0/0/0 -  {}
04:58:02 - ERROR	| exceptions.__init__:19 - 0/0/0 -  None
04:58:02 - DEBUG	| exceptions.__init__:20 - 0/0/0 -  NoneType: None

04:58:16 - DEBUG	| map.read_maps:96 - 0/0/0 -  []
04:58:16 - DEBUG	| map.read_maps:97 - 0/0/0 -  {}
04:58:19 - ERROR	| exceptions.__init__:19 - 0/0/0 -  你没下载地图，拿什么选？
04:58:19 - DEBUG	| exceptions.__init__:20 - 0/0/0 -  NoneType: None

**Comment by fanshu-520** [comment]
You need to check for updates first

**Comment by yxc0915** [comment]
I think you need to download the Chinese (Simplified) language pack before using this script to eliminate garbled characters and display correctly. Welcome to join the Telegram group for more help.

**Comment by yxc0915** [comment]
Before using this script, you need to obtain updates through program operations to download map and image resources, which will enable your script to run properly. However, it seems that you are unable to display it properly. Please download the Chinese Simplified language pack in the Windows settings now.

**Comment by yxc0915** [comment]
I have submitted an English version of the launcher program, but please note that only the English interface has been added, and the script still runs in Simplified Chinese. Please change the language to Simplified Chinese in the game settings.
