### ISSUE TITLE
[Bug] GUI启动无法操控游戏

### ISSUE THREAD

**Issue by yxc0915** [Starry-Wind/StarRailAssistant#390]
### 问题描述

使用GUI启动脚本后无法操控游戏，回到gui界面后，程序一直在按M，证明程序在运行

### 预期行为

能正常运行脚本

### 实际行为

未能成功操控游戏

### 截图或录屏

![QQ截图20230601090227](https://github.com/Starry-Wind/StarRailAssistant/assets/62410385/c64c8e46-fc4b-4d13-8d33-7535b0200cb8)

### 自动锄大地脚本版本

latest

### 星穹铁道区服

国服

### 日志

08:57:56 - INFO	| config.init_config_file:66 - 0/0/0 -  配置初始化
08:57:58 - DEBUG	| map.read_maps:96 - 0/0/0 -  []
08:57:58 - DEBUG	| map.read_maps:97 - 0/0/0 -  {}
08:58:08 - DEBUG	| map.read_maps:96 - 0/0/0 -  []
08:58:08 - DEBUG	| map.read_maps:97 - 0/0/0 -  {}
[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11619889/default.log)

**Comment by Night-stars-1** [comment]
本地测试正常运行，你如果一管理员方式启动gui
