### ISSUE TITLE
[功能请求] 图形界面对于新的依赖没装之类的异常加个弹窗警告或者能写入日志文件

### ISSUE THREAD

**Issue by zty1017** [Starry-Wind/StarRailAssistant#392]
### 原因

下午更新了脚本后发现打开图形界面直接闪退，命令行运行Honkai_Star_Rail.py"无异常，运行gui.py时报错发现是有新的依赖包没安装。希望图形界面对于新的依赖没装之类的异常加个弹窗警告或者能写入日志文件，直接闪退了不知道哪出了问题，日志文件也没有记录错误。

### 功能简述

图形界面对于新的依赖没装之类的异常加个弹窗警告或者能写入日志文件

### 功能逻辑

gui.py加入异常处理，运行时出现异常能有弹窗提示或者写入日志文件，直接运行start.exe出现异常时是直接闪退了。

**Comment by zty1017** [comment]
> ### 原因
> 下午更新了脚本后发现打开图形界面直接闪退，命令行运行Honkai_Star_Rail.py"无异常，运行gui.py时报错发现是有新的依赖包没安装。希望图形界面对于新的依赖没装之类的异常加个弹窗警告或者能写入日志文件，直接闪退了不知道哪出了问题，日志文件也没有记录错误。
> 
> ### 功能简述
> 图形界面对于新的依赖没装之类的异常加个弹窗警告或者能写入日志文件
> 
> ### 功能逻辑
> gui.py加入异常处理，运行时出现异常能有弹窗提示或者写入日志文件，直接运行start.exe出现异常时是直接闪退了。
> 
> ### 实现参考
> _No response_

另外，目前gui背景图主要是浅色偏白色的，然后字体也用的白色字，实际使用字很多是不太看得清的，更换背景或者更换字体颜色实际体验可能会好些
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/57761557/f2c059a3-046e-4681-afee-579ff814a4d7)

**Comment by yxc0915** [comment]
字体为白色是由于你开启了夜间模式，另外，我建议删除背景以自适应系统显示。
