### ISSUE TITLE
[Bug] 4K显示器应该如何设置？

### ISSUE THREAD

**Issue by AshenAshes** [Starry-Wind/StarRailAssistant#404]
### 问题描述

我的显示器分辨率为3840x2160 dpi200%
我将游戏分辨率分别设置为1920x1080全屏 和 1920x1080全屏窗口
角色停在在观景车厢
选择PC、大世界然后开始后，程序一直处于打开地图、退出地图的循环中，要么就是打开地图然后没有下一步动作
感觉是点击位置出现错误
请问我应该如何设置游戏分辨率？

### 预期行为

如上所述

### 实际行为

如上所述

### 自动锄大地脚本版本

main

### 星穹铁道区服

国服

### 日志

[Uploading 日志文件.log…]()

**Comment by Night-stars-1** [comment]
你的日志没有上传成功

**Comment by Night-stars-1** [comment]
> > 你的日志没有上传成功
> 
> [日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11645602/default.log) 不好意思，已重新上传

你的地图那是否有其他悬浮窗挡住了画面

**Comment by AshenAshes** [comment]
> > > 你的日志没有上传成功
> > 
> > 
> > [日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11645602/default.log) 不好意思，已重新上传
> 
> 你的地图那是否有其他悬浮窗挡住了画面

我确定之前没有悬浮窗挡住。在我拉取了这个[commit](https://github.com/Starry-Wind/StarRailAssistant/commit/9e1a5b0d28a21b1b73f7315c8a895e63fbb516c4)之后，程序可以正常运行了。
