### ISSUE TITLE
start.exe 無法使用[Bug] 

### ISSUE THREAD

**Issue by RedTea-Cup** [Starry-Wind/StarRailAssistant#407]
### Problem Description

程式運行后無事發生。建議使用bat：
cd 根目錄
Python Honkai_Star_Rail.py

### expected behavior

運行Honkai_Star_Rail.py

### actual behavior

空

### Honkai-Star-Rail version

v1.5.7

### Honkai Star Server

Global

### log

無日志記錄

**Comment by Night-stars-1** [comment]
所给信息过少，我无法知道具体原因
