### ISSUE TITLE
[bug] Assistant often just pauses in one of the maps in the third (green) world

### ISSUE THREAD

**Issue by dododon22** [Starry-Wind/StarRailAssistant#408]
### Problem Description

Is there a way for the game to check if it's paused or if the mouse moved by accident, to recalibrate itself properly so that it continues on to the last map? Thank you so much.

Regards,

### 是否使用三月七跑图

- [X] 是
- [ ] 否

**Comment by Xe-No** [comment]
It may caused by map waiting time out. If you install your game in HDD drive, loading time may excceed the max waiting time. 
It can be solved by extending the waiting time, if it's loading issues.

**Comment by Night-stars-1** [comment]
#587
