### ISSUE TITLE
[Bug] 1.1版本地图反复开关问题

### ISSUE THREAD

**Issue by wenbuer** [Starry-Wind/StarRailAssistant#409]
### 问题描述

1.1版本更新之后
完成残响回廊-1后，开始残响回廊-2锄地时，遇到地图M反复开关问题

OCR识别如下：
16:58:07 - DEBUG	| calculated.part_ocr:603 - 20230604205135/20230603155439/20230603155439 -  {'导凯': (414, 234), '推利洛-V': (450, 261), '10/': (545, 341)}
16:58:08 - DEBUG	| calculated.part_ocr:603 - 20230604205135/20230603155439/20230603155439 -  {'工': (532, 262)}

可能原因：
遇到新版本迷路的扑满导致位置偏移

### 预期行为

正常锄大地

### 实际行为

地图反复开关

### 自动锄大地脚本版本

20230604205135/20230603155439/20230603155439

### 星穹铁道区服

国服

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11676120/default.log)

**Comment by kz-wind** [comment]
不止一张地图出现这样的情况，我这边看从大矿区往后的地图都会出现这样的反复开关，但是手动点出游戏窗口外，脚本可以自动回正后重新进行跑图

**Comment by yxc0915** [comment]
看来是ocr的问题@Night-stars-1

**Comment by yxc0915** [comment]
干活咯@Night-stars-1

**Comment by AquaDeer10** [comment]
utils\calculated.py:711
`while True:`
`    if self.check_list(".*导.*航.*", map_status):`
`        break`
导航字体改变识别成了导凯，导致无限循环开关地图
先把`".*导.*航.*"`改为`".*导"`吧，能暂时解决问题

> 不止一张地图出现这样的情况，我这边看从大矿区往后的地图都会出现这样的反复开关，但是手动点出游戏窗口外，脚本可以自动回正后重新进行跑图

**Comment by wenbuer** [comment]
> utils\calculated.py:711 `while True:` ` if self.check_list(".*导.*航.*", map_status):` ` break` 导航字体改变识别成了导凯，导致无限循环开关地图 先把`".*导.*航.*"`改为`".*导"`吧，能暂时解决问题
> 
> > 不止一张地图出现这样的情况，我这边看从大矿区往后的地图都会出现这样的反复开关，但是手动点出游戏窗口外，脚本可以自动回正后重新进行跑图

可以解决识别问题
