### ISSUE TITLE
[路线错误] 模拟器未能正确移动和点击对应锚点

### ISSUE THREAD

**Issue by Asakushen** [Starry-Wind/StarRailAssistant#413]
### 问题描述

模拟器未能正确移动和点击对应锚点

模拟器新版本走路疑似被修改，ui界面疑似修改
ui界面通过修改模拟器自带的按键映射可以解决，但模拟器的移动貌似会先进行走路再奔跑导致线路出现错误

### 是否使用三月七跑图

- [X] 是
- [ ] 否

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11687201/default.log)

**Comment by Night-stars-1** [comment]
更新即可
