### ISSUE TITLE
现有adb代码在模拟器中可能会遇到截图不完整的问题

### ISSUE THREAD

**Issue by oTnTh** [Starry-Wind/StarRailAssistant#421]
### 问题描述

![screencast01](https://github.com/Starry-Wind/StarRailAssistant/assets/92753/c819a145-ec1d-440b-9caa-7f5a336bc652)

蓝叠模拟器，上图是我从`/sdcard/Pictures/screencast.png`复制出来的。

我是手柄党，当开一个自己远程自己跑助手，再开一个游戏的时候，两个游戏都会响应手柄操作，导致助手完全不能用，所以对手柄党来说模拟器方式还是有意义的。

我改了一下adb.py里的截图功能，不过可能还是需要一定的时间测试：

```python
    def screencast(self) -> Image:
        """
        说明:
            截图
        参数:
            :param path: 手机中截图保存位置
        """
        with os.popen('adb shell "screencap -p | busybox base64"') as fp:
            dat = base64.b64decode(fp.read())
        img = cv2.imdecode(np.frombuffer(dat, np.uint8), cv2.IMREAD_COLOR)
        return Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
```

原有的`path`参数我搜了一下代码，好像也完全没用上，所以就删掉了。

`screencap -p`输出的是二进制数据，但是在Windows里直接读会遇到`\r\n`的问题。鉴于在Mac或者Linux里跑模拟器也不是没可能，所以可能还是base64中转一下好些。

另外issue类型是不是也改一下，像这个问题就不是功能要求也不是路线错误。

### 是否使用三月七跑图

- [ ] 是
- [ ] 否

### 日志

无

**Comment by Night-stars-1** [comment]
好的，更新反馈
bug的issue因为配置错误没有了

**Comment by Night-stars-1** [comment]
你好截图不完整的问题是因为你在程序截图输出的时候关闭了程序，导致图片数据不全
在模拟器的`/sdcard/Pictures/screencast.png`中图片应该是全的

**Comment by oTnTh** [comment]
> 你好截图不完整的问题是因为你在程序截图输出的时候关闭了程序，导致图片数据不全 在模拟器的`/sdcard/Pictures/screencast.png`中图片应该是全的

应该不是你说的这种情况。

我是尝试用模拟器挂助手的时候，发现助手停在那里很久都没有进一步的动作，去追查原因的时候才发现截图不完整的问题。

而且前面我也有说明，贴出来的这一张就是从`/sdcard/Pictures/screencast.png`复制出来的。

**Comment by oTnTh** [comment]
另外还有一点，我昨天测试自己改的那个函数的时候，每一张截图都保存下来了没删。一轮大世界下来，我发现截图一共有好几G大小，从延长固态硬盘的寿命考虑也没有往硬盘写的必要。
