### ISSUE TITLE
6/9更新资源后无法侦测到游戏

### ISSUE THREAD

**Issue by LekaOuO** [Starry-Wind/StarRailAssistant#423]
### 问题描述

![螢幕擷取畫面 2023-06-09 230800](https://github.com/Starry-Wind/StarRailAssistant/assets/132276251/7b9166c8-a18a-4090-ab82-40bc54eb45e2)
今天(6/9)更新资源后无法顺利侦测到游戏
已确认游戏有开启且之前都能顺利运行

排查：
我先下载了1.5.9版本法先无法侦测到游戏，之后又切换回之前一直能用的1.5.7版本并更新资源后发现一样无法侦测到游戏
之后测试一下游戏里切换繁体语言后能顺利侦测到游戏，但会一直打开/关闭地图无限重复

### 是否使用三月七跑图

- [X] 是
- [ ] 否

### 日志

[日誌文件.2023-06-10_00-30-43_355674.log](https://github.com/Starry-Wind/StarRailAssistant/files/11708622/2023-06-10_00-30-43_355674.log)
[日誌文件.2023-06-10_00-35-01_385971.log](https://github.com/Starry-Wind/StarRailAssistant/files/11708623/2023-06-10_00-35-01_385971.log)

日誌文件.2023-06-10_00-30-43_355674是游戏语言为简体中文时无法顺利侦测到游戏

日誌文件.2023-06-10_00-35-01_385971是游戏语言切换为繁体中文可以侦测到游戏，但第一步就会在打开地图跟关闭地图间反复

**Comment by Night-stars-1** [comment]
#424
