### ISSUE TITLE
[功能请求] 建议加快等待进入地图的识别超时，避免遇到进图被怪物攻击卡图

### ISSUE THREAD

**Issue by cdcp998** [Starry-Wind/StarRailAssistant#427]
### 原因

15:43:15 - INFO	| calculated.wait_join:728 - 0/20230609170408/20230609170408 -  识别超时
15:43:15 - INFO	| map.auto_map:131 - 0/20230609170408/20230609170408 -  地图加载完毕，加载时间为 30.033862113952637 秒

### 功能简述

识别等待时间太长会卡图。建议设置在5-10秒内

### 功能逻辑

1

**Comment by Night-stars-1** [comment]
#432
