### ISSUE TITLE
[Bug] import模组失败的后续处理

### ISSUE THREAD

**Issue by zeronsama** [Starry-Wind/StarRailAssistant#455]
### 问题描述

某次脚本更新之后，需要import新的模块(比如说上次好像更新了pluggy模块)，我翻阅了一下源代码，发现import失败后是通过
```py
os.system("pip install -r requirements.txt")
```
来添加新的包，但是这会出现一个问题，我系统中有多个python版本，默认使用py3.9，而小助手使用py3.11

### 预期行为

正确识别当前使用的python版本，并使用对应的pip

### 实际行为

错误地使用了py3.9的pip

### 自动锄大地脚本版本

20230604205135

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

.

**Comment by Night-stars-1** [comment]
安装python依赖本就不应该是python程序所应该完成的事情，你在其他项目里都不会看见这样的代码，这些写实属无奈，我认为他不应该重新在python中
用户应该学习python的基础知识，并且自己处理依赖问题，而不是交给程序
