### ISSUE TITLE
[Bug] 多张地图选择传送锚点时出现无法选中情况

### ISSUE THREAD

**Issue by Serein1202** [Starry-Wind/StarRailAssistant#457]
### 问题描述

当锚点选择出现两个方框或以上情况时，无法选中相关传送锚点，并且会自动回到主控舱段地图，控制台会显示地图识别超时。目前已知的有收容舱段-3，支援舱段-1，支援舱段-2，支援舱段-3，支援舱段-4，残响回廊-2...

模拟器分辨率1280x720，游戏分辨率中，光照强度非常高。

### 预期行为

选中正确地图和锚点并传送，正确进入地图并开始相关任务

### 实际行为

无法选中相关锚点，会自动换到主控舱段页，控制台输出识别地图超时字样。需要手动选择程序事先设置的正确的传送锚点，程序识别到才会自动进行下一步传送。若一直不手动识别，后台会一直重复识别，windows并出现蓝屏情况自动重启

### 截图或录屏

https://github.com/Starry-Wind/StarRailAssistant/assets/33860649/b52db98f-bd8d-4e74-be8f-192af5a82b18

### 自动锄大地脚本版本

v1.6.1

### 星穹铁道区服

国服

### 运行的客户端

模拟器

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11720521/default.log)

**Comment by Night-stars-1** [comment]
已修复#458
