### ISSUE TITLE
打开地图传送如果有选项程序无法正确选择传送

### ISSUE THREAD

**Issue by R88624332** [Starry-Wind/StarRailAssistant#461]
### 问题描述

打开地图传送如果有选项程序无法正确选择传送

### 预期行为

选择某一个传送点传送

### 实际行为

保持在地图界面

### 截图或录屏

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/85300814/6b2fe6e2-99c3-4ec7-beb6-0a8f9ecb2351)
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/85300814/f0d694e3-898b-415a-81e8-a35c93943dcd)

### 自动锄大地脚本版本

1.6.1

### 星穹铁道区服

国服

### 运行的客户端

模拟器

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11730125/default.log)

**Comment by Night-stars-1** [comment]
这应该是你的错误操作，程序还没有开始选择传送点

**Comment by Night-stars-1** [comment]
好像是因为图片变了一点，导致匹配度下降，改用ocr了，应该可以了
