### ISSUE TITLE
[功能请求] 希望作者加一个自动关机功能

### ISSUE THREAD

**Issue by Ikeltis** [Starry-Wind/StarRailAssistant#470]
### 原因

有时候不好预计锄地结束时间，设定关机时间不准确

### 功能简述

在选择大世界锄地后新增一个选项，是否锄地结束后自动关机，选是则锄地完成后自动关机

### 功能逻辑

在选择大世界锄地后新增一个选项，是否锄地结束后自动关机，选是则锄地完成后自动关机

**Comment by Night-stars-1** [comment]
https://github.com/Night-stars-1/sra_plugins_shutdown
