### ISSUE TITLE
更新地图显示map\map_3-4_7.json发现文件缺失，直接运行脚本报错

### ISSUE THREAD

**Issue by 6mod9** [Starry-Wind/StarRailAssistant#472]
### 问题描述

今天更新之后不能运行脚本了

### 预期行为

脚本成功运行

### 实际行为

红字报错

### 截图或录屏

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/57243904/bf1932b7-1672-44de-b047-e19ac2fa07b7)

### 自动锄大地脚本版本

20230615125708/20230615125906/20230615125906

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11753177/default.log)

**Comment by Night-stars-1** [comment]
更新一下
