### ISSUE TITLE
[Bug] 如果commit中删除了某条路线，客户端更新地图不会自动删除这条路线，导致卡图

### ISSUE THREAD

**Issue by Xe-No** [Starry-Wind/StarRailAssistant#476]
### 问题描述

如果commit中删除了某条路线，客户端更新地图不会自动删除这条路线，导致卡图

### 预期行为

commit中删除了某条路线后，客户端更新也应该删除这条路线

### 实际行为

commit中删除了某条路线后，客户端更新没有删除这条路线，可能是直接解压压缩包内的资源覆盖造成的。
目前暂时可以通过录制空操作来对应该删掉的路线近战占位来解决。
长久来看应该在每次更新路线时删除commit后没有的路线。

### 自动锄大地脚本版本

1.6.2

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

N/A

**Comment by Night-stars-1** [comment]
已更改

**Comment by Xe-No** [comment]
我也记得之前会删，不过图片和地图都是子文件夹，现在这样就挺好。
