### ISSUE TITLE
地图读取顺序错误

### ISSUE THREAD

**Issue by EnderOre** [Starry-Wind/StarRailAssistant#484]
### 问题描述

地图读取顺序错误，导致1-1_1的基座舱段刷完后直接跳到城郊雪原-2
于是脚本会停下来。

### 预期行为

1-1_1直接顺利过渡到1-2_1

### 实际行为

附上读取地图顺序：
10:18:23 - DEBUG	| map.read_maps:101 - 20230616053922/20230616033452/20230616033452 -  ['map_1-3_3.json', 'map_2-7_1.json', 'map_1-2_1.json', 'map_1-3_1.json', 'map_3-1_3.json', 'map_2-3_3.json', 'map_2-5_4.json', 'map_3-4_4.json', 'map_3-4_5.json', 'map_3-2_1.json', 'map_2-2_2.json', 'map_2-7_2.json', 'map_1-2_2.json', 'map_3-4_6.json', 'map_3-4_1.json', 'map_3-1_2.json', 'map_2-5_2.json', 'map_2-6_1.json', 'map_2-4_1.json', 'map_2-5_1.json', 'map_2-3_2.json', 'map_3-3_4.json', 'map_3-1_5.json', 'map_3-4_7.json', 'map_3-3_3.json', 'map_3-3_1.json', 'map_2-2_1.json', 'map_3-3_2.json', 'map_3-1_6.json', 'map_3-2_5.json', 'map_3-4_3.json', 'map_1-3_4.json', 'map_2-3_5.json', 'map_2-3_4.json', 'map_3-2_3.json', 'map_2-6_2.json', 'map_2-5_3.json', 'map_1-3_2.json', 'map_3-2_4.json', 'map_2-7_3.json', 'map_1-2_3.json', 'map_3-1_1.json', 'map_3-4_2.json', 'map_3-1_4.json', 'map_2-3_1.json', 'map_2-1_1.json', 'map_3-2_2.json', 'map_1-1_1.json', 'map_2-1_2.json', 'map_2-4_2.json']
10:18:23 - DEBUG	| map.read_maps:102 - 20230616053922/20230616033452/20230616033452 -  {'1': {'3_3': '支援舱段-3', '2_1': '收容舱段-1', '3_1': '支援舱段-1', '2_2': '收容舱段-2', '3_4': '支援舱段-4', '3_2': '支援舱段-2', '2_3': '收容舱段-3', '1_1': '基座舱段-1'}, '2': {'7_1': '机器聚落-1', '3_3': '残响回廊-3', '5_4': '大矿区-4', '2_2': '边缘道路-2', '7_2': '机器聚落-2', '5_2': '大矿区-2', '6_1': '铆钉镇-1', '4_1': '永冬岭-1', '5_1': '大矿区-1', '3_2': '残响回廊-2', '2_1': '边缘道路-1', '3_5': '残响回廊-5', '3_4': '残响回廊-4', '6_2': '铆钉镇-2', '5_3': '大矿区-3', '7_3': '机器聚落-3', '3_1': '残响回廊-1', '1_1': '城郊雪原-1', '1_2': '城郊雪原-2', '4_2': '永冬岭-2'}, '3': {'1_3': '流云渡-3', '4_4': '工造司-4', '4_5': '工造司-5', '2_1': '迥星港-1', '4_6': '工造司-6', '4_1': '工造司-1', '1_2': '流云渡-2', '3_4': '太卜司-4', '1_5': '流云渡-5', '4_7': '工造司-7', '3_3': '太卜司-3', '3_1': '太卜司-1', '3_2': '太卜司-2', '1_6': '流云渡-6', '2_5': '迥星港-5', '4_3': '工造司-3', '2_3': '迥星港-3', '2_4': '迥星港-4', '1_1': '流云渡-1', '4_2': '工造司-2', '1_4': '流云渡-4', '2_2': '迥星港-2'}}

### 截图或录屏

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/66881284/3b72fd79-788c-4f77-a6de-ac3800bd9f9a)

### 自动锄大地脚本版本

1.6.3

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11765521/default.log)

**Comment by Xe-No** [comment]
地图缺失，请更新地图后，再检查

**Comment by EnderOre** [comment]
这是最新的地图做出来的日志，没有更新的版本了
然后是按照正常情况来说应该是按照地图的名字顺序来跑图的我这明显并不是
map_1-3_3.json', 'map_2-7_1.json', 'map_1-2_1.json', 'map_1-3_1.json', 'map_3-1_3.json', 'map_2-3_3.json', 'map_2-5_4.json', 'map_3-4_4.json', 'map_3-4_5.json', 'map_3-2_1.json', 'map_2-2_2.json', 'map_2-7_2.json', 'map_1-2_2.json', 'map_3-4_6.json', 'map_3-4_1.json', 'map_3-1_2.json', 'map_2-5_2.json', 'map_2-6_1.json', 'map_2-4_1.json', 'map_2-5_1.json', 'map_2-3_2.json', 'map_3-3_4.json', 'map_3-1_5.json', 'map_3-4_7.json', 'map_3-3_3.json', 'map_3-3_1.json', 'map_2-2_1.json', 'map_3-3_2.json', 'map_3-1_6.json', 'map_3-2_5.json', 'map_3-4_3.json', 'map_1-3_4.json', 'map_2-3_5.json', 'map_2-3_4.json', 'map_3-2_3.json', 'map_2-6_2.json', 'map_2-5_3.json', 'map_1-3_2.json', 'map_3-2_4.json', 'map_2-7_3.json', 'map_1-2_3.json', 'map_3-1_1.json', 'map_3-4_2.json', 'map_3-1_4.json', 'map_2-3_1.json', 'map_2-1_1.json', 'map_3-2_2.json', 'map_1-1_1.json', 'map_2-1_2.json', 'map_2-4_2.json

**Comment by EnderOre** [comment]
发现了。这是map分支里的map_list文件里的地图顺序。我这里的程序就直接吧这个顺序当作打大世界顺序了。
[map_list.txt](https://github.com/Starry-Wind/StarRailAssistant/files/11771185/map_list.txt)

我这里是直接坏了。所以说能不能给map_list.json里的顺序调正常点。

**Comment by EnderOre** [comment]
看上去有可能像是我这里的排序坏了。

**Comment by Night-stars-1** [comment]
更新试一下
https://github.com/Starry-Wind/StarRailAssistant/blob/1ef8c23323743fecb0396f9f0930f87488810470/utils/map.py#L106

**Comment by Night-stars-1** [comment]
无人应答，关闭issues

**Comment by EnderOre** [comment]
新map的sort消失了，又不能用了
