### ISSUE TITLE
地图选择后无法进入

### ISSUE THREAD

**Issue by JianangZhao** [Starry-Wind/StarRailAssistant#500]
### 问题描述

启动脚本后 系统开始选择选择雅利洛六号地图 但是一直开在雅利洛六号地图地图选择界面 无法进入 似乎光标无法聚焦

### 预期行为

选择选择雅利洛六号地图后 自动进入小地图

### 实际行为

一直卡在选择选择雅利洛六号地图选择界面， 查看日志 一直打印09:07:56 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9006977081298828

 

### 截图或录屏

![屏幕截图 2023-06-18 090808](https://github.com/Starry-Wind/StarRailAssistant/assets/34386646/4c4828c6-fd67-4c42-af0a-5f26bad96033)

### 自动锄大地脚本版本

main -- Commits on Jun 17, 2023

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

09:07:49 - INFO	| calculated.click_target:407 - 20230611181439/20230616033452/20230610185404 -  地图识别超时
09:07:49 - INFO	| calculated.click_target:413 - 20230611181439/20230616033452/20230610185404 -  map_2-3
09:07:50 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9000011682510376
09:07:50 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9000596404075623
09:07:51 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9000481963157654
09:07:52 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9000674486160278
09:07:52 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9000408053398132
09:07:53 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.8999781012535095
09:07:54 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.899993360042572
09:07:54 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.900061845779419
09:07:55 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9001162052154541
09:07:55 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9006977081298828
09:07:56 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9006977081298828
09:07:57 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9006977677345276
09:07:57 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9006977081298828
09:07:58 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9006978273391724
09:07:59 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9006977081298828
09:07:59 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9006978273391724
09:08:00 - INFO	| calculated.click_target:419 - 20230611181439/20230616033452/20230610185404 -  0.9006977081298828

**Comment by ddr850814** [comment]
一样情况 不过我卡在3-2了

**Comment by Night-stars-1** [comment]
你无法从非-1结尾的地图直接启动脚本
