### ISSUE TITLE
[Bug] 部分地图无法打开星轨航图，例如永冬岭2，手点一下可以继续

### ISSUE THREAD

**Issue by z134git** [Starry-Wind/StarRailAssistant#503]
### 问题描述

12:31:31 - INFO	| calculated.ocr_click:202 - 20230618110943/20230616033452/20230616033452 -  识别超时
12:31:31 - DEBUG	| map.auto_map:112 - 20230618110943/20230616033452/20230616033452 -  temp\orientation_4.png
12:31:32 - INFO	| calculated.click_target:413 - 20230618110943/20230616033452/20230616033452 -  orientation_4
12:31:33 - INFO	| calculated.click_target:419 - 20230618110943/20230616033452/20230616033452 -  0.9422474503517151
12:31:33 - INFO	| calculated.click_target:419 - 20230618110943/20230616033452/20230616033452 -  0.9422474503517151
12:31:34 - INFO	| calculated.click_target:419 - 20230618110943/20230616033452/20230616033452 -  0.9422474503517151
12:31:35 - INFO	| calculated.click_target:419 - 20230618110943/20230616033452/20230616033452 -  0.9422474503517151
12:31:35 - INFO	| calculated.click_target:419 - 20230618110943/20230616033452/20230616033452 -  0.9422474503517151
12:31:36 - INFO	| calculated.click_target:419 - 20230618110943/20230616033452/20230616033452 -  0.9422474503517151
12:31:37 - INFO	| calculated.click_target:419 - 20230618110943/20230616033452/20230616033452 -  0.9422474503517151
12:31:37 - INFO	| calculated.click_target:419 - 20230618110943/20230616033452/20230616033452 -  0.9422474503517151
12:31:38 - INFO	| calculated.click_target:419 - 20230618110943/20230616033452/20230616033452 -  0.9422473311424255
12:31:39 - INFO	| calculated.click_target:419 - 20230618110943/20230616033452/20230616033452 -  0.942247211933136
12:31:39 - INFO	| calculated.click_target:419 - 20230618110943/20230616033452/20230616033452 -  0.942247211933136
12:31:40 - INFO	| calculated.click_target:419 - 20230618110943/20230616033452/20230616033452 -  0.9422473311424255

### 预期行为

点击星轨航图

### 实际行为

鼠标不移动，卡在地图界面中心

### 自动锄大地脚本版本

1 63及preview

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11780746/default.log)

**Comment by Night-stars-1** [comment]
目前只正常从-1开始地图
