### ISSUE TITLE
[Bug] 目前选择模拟器运行无法正常加载地图

### ISSUE THREAD

**Issue by ShanshanHY** [Starry-Wind/StarRailAssistant#504]
### 问题描述

当前使用git clone项目，更新全部文件后选择模拟器启动，脚本提示没有地图

经测试，使用PC模式启动无此问题

查看代码和commit记录，发现16小时前的 PR [#489](https://github.com/Starry-Wind/StarRailAssistant/pull/489/files#diff-2285afabac772ea4b972efbefe6b84146db7671d567afb2204f7e3e2f3ae7e1b) 新增了针对模拟器的地图判断

但判断过程与之前 PR #401 提到的方法不同，PC直接读取`/map`下的地图文件，模拟器直接读取`/map/mnq`下的地图文件，而当前并没有内置模拟器配置文件导致加载失败

### 预期行为

模拟器正常读取地图并开始

### 实际行为

脚本运行中跳过/map直接从/map/mnq下读取配置文件，但目前/map/mnq下并无任何配置文件

### 截图或录屏

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/29966961/aa14a0f9-e031-4211-ae73-d123ab9ae6bd)

### 自动锄大地脚本版本

最新main分支

### 星穹铁道区服

国服

### 运行的客户端

模拟器

### 日志

[运行日志](https://github.com/Starry-Wind/StarRailAssistant/files/11780843/default.log)

**Comment by Night-stars-1** [comment]
我们无力继续pc和模拟器多平台兼容，所以放弃模拟器，不定时维护，如果要使用模拟器可以将map移入mnq文件夹内

**Comment by ShanshanHY** [comment]
好的，了解了
