### ISSUE TITLE
[Bug] 录制的JSON中如果有F键相关的，模拟器没有处理该逻辑

### ISSUE THREAD

**Issue by coolxll** [Starry-Wind/StarRailAssistant#510]
### 问题描述

如支援舱段下楼电梯、工造司和太卜司的入画传送，会导致卡图
如非必要录制时建议避开f，走其他路径录制，可以有更大的兼容性

### 预期行为

f行为在pc和模拟器（adb）上表现一致

### 实际行为

adb上f键被直接丢弃了

### 自动锄大地脚本版本

01febb392384ef16e66afce3b39ac4404cbdf5d6 6月9号的版本

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

map.auto_map:131 - 20230604205135/20230616033452/20230616033452 - 地图加载完毕，加载时间为 0.9067051410675049 秒
map.start_map:54 - 20230604205135/20230616033452/20230616033452 - 开始寻路
map.start_map:56 - 20230604205135/20230616033452/20230616033452 - 执行map_3-1_1文件:1/23 {'w': 8.906384468078613}
map.start_map:56 - 20230604205135/20230616033452/20230616033452 - 执行map_3-1_1文件:2/23 {'d': 9.646476030349731}
map.start_map:56 - 20230604205135/20230616033452/20230616033452 - 执行map_3-1_1文件:3/23 {'a': 0.7295119762420654}
map.start_map:56 - 20230604205135/20230616033452/20230616033452 - 执行map_3-1_1文件:4/23 {'w': 4.944909334182739}
map.start_map:56 - 20230604205135/20230616033452/20230616033452 - 执行map_3-1_1文件:5/23 {'d': 2.397244024276733}
map.start_map:56 - 20230604205135/20230616033452/20230616033452 - 执行map_3-1_1文件:6/23 {'fighting': 1}

**Comment by cdcp998** [comment]
看了看代码。。就没写模拟器的入画操作。。

**Comment by cdcp998** [comment]
检测了下代码。。发现压根没写模拟器的入画操作。。
