### ISSUE TITLE
[Bug] 大矿区卡死

### ISSUE THREAD

**Issue by gongfuture** [Starry-Wind/StarRailAssistant#514]
### 问题描述

锄地运行至大矿区区域程序卡死
由于人不在电脑前，所以虽然能保证没有动键鼠，但是也不知道发生了什么，只有log和最后地区截图
问题出现于日志6435行

### 预期行为

正常进行大矿区锄地

### 实际行为

程序卡死

### 截图或录屏

<img width="960" alt="Snipaste_2023-06-19_16-40-14" src="https://github.com/Starry-Wind/StarRailAssistant/assets/60888755/cad6f3c1-3ae2-4c8f-93db-71c04b8ce385">
<img width="960" alt="Snipaste_2023-06-19_16-40-22" src="https://github.com/Starry-Wind/StarRailAssistant/assets/60888755/22bb4f01-6acb-4e1b-9210-76ec535891b3">

### 自动锄大地脚本版本

2.7_test

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

[战斗日志.log](https://github.com/Starry-Wind/StarRailAssistant/files/11786177/default.log)
[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11786179/default.log)

**Comment by cdcp998** [comment]
#513 尝试修复
