### ISSUE TITLE
[Bug]更新1.6.4后地图读取顺序错误

### ISSUE THREAD

**Issue by EnderOre** [Starry-Wind/StarRailAssistant#525]
### 问题描述

[#484](https://github.com/Starry-Wind/StarRailAssistant/issues/484)通过在map.py中使用sort已修复。更新1.6.4以后map.py里的sort消失，目前本人的地图又混乱了，1-1基座舱段打完自动进入城郊雪原。

（怎么更新了又坏了。好不容易爽了一晚上，今天更新了一下脚本快乐又消失了。
附上之前加上sort的图片
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/66881284/62fae8ef-7955-470b-9e79-6ef2b57c313f)

### 预期行为

1-1_1直接顺利过渡到1-2_1

### 实际行为

附上读取地图顺序：
10:18:23 - DEBUG | map.read_maps:101 - 20230616053922/20230616033452/20230616033452 - ['map_1-3_3.json', 'map_2-7_1.json', 'map_1-2_1.json', 'map_1-3_1.json', 'map_3-1_3.json', 'map_2-3_3.json', 'map_2-5_4.json', 'map_3-4_4.json', 'map_3-4_5.json', 'map_3-2_1.json', 'map_2-2_2.json', 'map_2-7_2.json', 'map_1-2_2.json', 'map_3-4_6.json', 'map_3-4_1.json', 'map_3-1_2.json', 'map_2-5_2.json', 'map_2-6_1.json', 'map_2-4_1.json', 'map_2-5_1.json', 'map_2-3_2.json', 'map_3-3_4.json', 'map_3-1_5.json', 'map_3-4_7.json', 'map_3-3_3.json', 'map_3-3_1.json', 'map_2-2_1.json', 'map_3-3_2.json', 'map_3-1_6.json', 'map_3-2_5.json', 'map_3-4_3.json', 'map_1-3_4.json', 'map_2-3_5.json', 'map_2-3_4.json', 'map_3-2_3.json', 'map_2-6_2.json', 'map_2-5_3.json', 'map_1-3_2.json', 'map_3-2_4.json', 'map_2-7_3.json', 'map_1-2_3.json', 'map_3-1_1.json', 'map_3-4_2.json', 'map_3-1_4.json', 'map_2-3_1.json', 'map_2-1_1.json', 'map_3-2_2.json', 'map_1-1_1.json', 'map_2-1_2.json', 'map_2-4_2.json']
10:18:23 - DEBUG | map.read_maps:102 - 20230616053922/20230616033452/20230616033452 - {'1': {'3_3': '支援舱段-3', '2_1': '收容舱段-1', '3_1': '支援舱段-1', '2_2': '收容舱段-2', '3_4': '支援舱段-4', '3_2': '支援舱段-2', '2_3': '收容舱段-3', '1_1': '基座舱段-1'}, '2': {'7_1': '机器聚落-1', '3_3': '残响回廊-3', '5_4': '大矿区-4', '2_2': '边缘道路-2', '7_2': '机器聚落-2', '5_2': '大矿区-2', '6_1': '铆钉镇-1', '4_1': '永冬岭-1', '5_1': '大矿区-1', '3_2': '残响回廊-2', '2_1': '边缘道路-1', '3_5': '残响回廊-5', '3_4': '残响回廊-4', '6_2': '铆钉镇-2', '5_3': '大矿区-3', '7_3': '机器聚落-3', '3_1': '残响回廊-1', '1_1': '城郊雪原-1', '1_2': '城郊雪原-2', '4_2': '永冬岭-2'}, '3': {'1_3': '流云渡-3', '4_4': '工造司-4', '4_5': '工造司-5', '2_1': '迥星港-1', '4_6': '工造司-6', '4_1': '工造司-1', '1_2': '流云渡-2', '3_4': '太卜司-4', '1_5': '流云渡-5', '4_7': '工造司-7', '3_3': '太卜司-3', '3_1': '太卜司-1', '3_2': '太卜司-2', '1_6': '流云渡-6', '2_5': '迥星港-5', '4_3': '工造司-3', '2_3': '迥星港-3', '2_4': '迥星港-4', '1_1': '流云渡-1', '4_2': '工造司-2', '1_4': '流云渡-4', '2_2': '迥星港-2'}}

### 截图或录屏

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/66881284/00bca878-d517-42ef-b878-312821eb6848)

### 自动锄大地脚本版本

1.6.4

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11790726/default.log)

**Comment by EnderOre** [comment]
01:24:29 - DEBUG	| config.read_maps:176 - 20230619230014/20230620003020/20230620003020 -  ['map_1-3_3.json', 'map_2-7_1.json', 'map_1-2_1.json', 'map_1-3_1.json', 'map_3-1_3.json', 'map_2-3_3.json', 'map_2-5_4.json', 'map_3-4_4.json', 'map_3-4_5.json', 'map_3-2_1.json', 'map_2-2_2.json', 'map_2-7_2.json', 'map_1-2_2.json', 'map_3-4_6.json', 'map_3-4_1.json', 'map_3-1_2.json', 'map_2-5_2.json', 'map_2-6_1.json', 'map_2-4_1.json', 'map_2-5_1.json', 'map_2-3_2.json', 'map_3-3_4.json', 'map_3-1_5.json', 'map_3-4_7.json', 'map_3-3_3.json', 'map_3-3_1.json', 'map_2-2_1.json', 'map_3-3_2.json', 'map_3-1_6.json', 'map_3-2_5.json', 'map_3-4_3.json', 'map_1-3_4.json', 'map_2-3_5.json', 'map_2-3_4.json', 'map_3-2_3.json', 'map_2-6_2.json', 'map_2-5_3.json', 'map_1-3_2.json', 'map_3-2_4.json', 'map_2-7_3.json', 'map_1-2_3.json', 'map_3-1_1.json', 'map_3-4_2.json', 'map_3-1_4.json', 'map_2-3_1.json', 'map_2-1_1.json', 'map_3-2_2.json', 'map_1-1_1.json', 'map_2-1_2.json', 'map_2-4_2.json', 'map_1-3_3.json', 'map_2-7_1.json', 'map_1-2_1.json', 'map_1-3_1.json', 'map_3-1_3.json', 'map_2-3_3.json', 'map_2-5_4.json', 'map_3-4_4.json', 'map_3-4_5.json', 'map_3-2_1.json', 'map_2-2_2.json', 'map_2-7_2.json', 'map_1-2_2.json', 'map_3-4_6.json', 'map_3-4_1.json', 'map_3-1_2.json', 'map_2-5_2.json', 'map_2-6_1.json', 'map_2-4_1.json', 'map_2-5_1.json', 'map_2-3_2.json', 'map_3-3_4.json', 'map_3-1_5.json', 'map_3-4_7.json', 'map_3-3_3.json', 'map_3-3_1.json', 'map_2-2_1.json', 'map_3-3_2.json', 'map_3-1_6.json', 'map_3-2_5.json', 'map_3-4_3.json', 'map_1-3_4.json', 'map_2-3_5.json', 'map_2-3_4.json', 'map_3-2_3.json', 'map_2-6_2.json', 'map_2-5_3.json', 'map_1-3_2.json', 'map_3-2_4.json', 'map_2-7_3.json', 'map_1-2_3.json', 'map_3-1_1.json', 'map_3-4_2.json', 'map_3-1_4.json', 'map_2-3_1.json', 'map_2-1_1.json', 'map_3-2_2.json', 'map_1-1_1.json', 'map_2-1_2.json', 'map_2-4_2.json']
01:24:29 - DEBUG	| config.read_maps:177 - 20230619230014/20230620003020/20230620003020 -  {'1': {'3_3': '支援舱段-3', '2_1': '收容舱段-1', '3_1': '支援舱段-1', '2_2': '收容舱段-2', '3_4': '支援舱段-4', '3_2': '支援舱段-2', '2_3': '收容舱段-3', '1_1': '基座舱段-1'}, '2': {'7_1': '机器聚落-1', '3_3': '残响回廊-3', '5_4': '大矿区-4', '2_2': '边缘道路-2', '7_2': '机器聚落-2', '5_2': '大矿区-2', '6_1': '铆钉镇-1', '4_1': '永冬岭-1', '5_1': '大矿区-1', '3_2': '残响回廊-2', '2_1': '边缘道路-1', '3_5': '残响回廊-5', '3_4': '残响回廊-4', '6_2': '铆钉镇-2', '5_3': '大矿区-3', '7_3': '机器聚落-3', '3_1': '残响回廊-1', '1_1': '城郊雪原-1', '1_2': '城郊雪原-2', '4_2': '永冬岭-2'}, '3': {'1_3': '流云渡-3', '4_4': '工造司-4', '4_5': '工造司-5', '2_1': '迥星港-1', '4_6': '工造司-6', '4_1': '工造司-1', '1_2': '流云渡-2', '3_4': '太卜司-4', '1_5': '流云渡-5', '4_7': '工造司-7', '3_3': '太卜司-3', '3_1': '太卜司-1', '3_2': '太卜司-2', '1_6': '流云渡-6', '2_5': '迥星港-5', '4_3': '工造司-3', '2_3': '迥星港-3', '2_4': '迥星港-4', '1_1': '流云渡-1', '4_2': '工造司-2', '1_4': '流云渡-4', '2_2': '迥星港-2'}}

**Comment by EnderOre** [comment]
刚才尝试了将旧版的map.py替换，出现了下文的情况。反正就是我自己没法退回了
PS E:\Star Rail\StarRailAssistant-1.6.3> Python Honkai_Star_Rail.py
Traceback (most recent call last):
  File "E:\Star Rail\StarRailAssistant-1.6.3\Honkai_Star_Rail.py", line 21, in <module>
    from utils.map import Map as map_word
  File "E:\Star Rail\StarRailAssistant-1.6.3\utils\map.py", line 22
    self.mouse = self.calculated。mouse
                                ^
SyntaxError: invalid character '。' (U+3002)

**Comment by Night-stars-1** [comment]
已经修复 #526
