### ISSUE TITLE
[Bug] 是上一个我提的大矿区bug延申

### ISSUE THREAD

**Issue by gongfuture** [Starry-Wind/StarRailAssistant#529]
### 问题描述

是https://github.com/Starry-Wind/StarRailAssistant/issues/514 这个issue的延申，我今天试验了一下可以稳定复现，使用的是67591c494b0e9e03fb803cb04fdccf5d4caf53c4提交
视频记录太大，走网盘了
链接：https://pan.baidu.com/s/1ZDwFBPoQAGmOvfc6zbqlCg?pwd=yhsf 
提取码：yhsf 
--来自百度网盘超级会员V6的分享
log放在下面了

### 预期行为

。

### 实际行为

识别错误

### 自动锄大地脚本版本

2.7_test

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11798568/default.log)
[战斗日志.log](https://github.com/Starry-Wind/StarRailAssistant/files/11798569/default.log)

**Comment by dododon22** [comment]
Same issue for me, heres my log
[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11805426/default.log)

**Comment by gongfuture** [comment]
> Same issue for me, heres my log [日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11805426/default.log)

我昨天还在想会不会是我自己的问题，原本准备再找一台pc测试一下，现在看来不是
I was wondering yesterday if it was my own problem, and I was going to find another PC to test it, but now it seems that it is not

**Comment by Klamist** [comment]
OCR识别错误……旧版的我记得是纯匹配图的，不知道有什么地方可以改

**Comment by Klamist** [comment]
目前的方案：
找到这一段，然后给星轨航图这一行前面加#，就不用ocr了，改用匹配图片了。
```
temp_ocr = {
            【在这里加一个“#”】"orientation_1": _("星轨航图"),
            #"orientation_2": _("空间站「黑塔"),
            "map_1": _("基座舱段"),
```

**Comment by nyano** [comment]
已连续复现2天，100%复现。即使手动跳到仙舟地图执行，仍然最后跑到大矿区卡死。
另外今天不知道为什么，最后还能打开esc菜单，或者进入物品菜单或合成菜单。(我是挂机的)
还有请求有个开关能手动关闭查漏补缺功能。现阶段由于不断的前期地图重复或者错误中断，造成后续的地图无法继续执行。
=》或者先首先完成整个地图流程后，再针对未正确执行的地图重复运行。
=》即使手动选择了从某个地图执行，但是查漏功能似乎仍然从第一个地图开始重复执行。

**Comment by Night-stars-1** [comment]
> 已连续复现2天，100%复现。即使手动跳到仙舟地图执行，仍然最后跑到大矿区卡死。 另外今天不知道为什么，最后还能打开esc菜单，或者进入物品菜单或合成菜单。(我是挂机的) 还有请求有个开关能手动关闭查漏补缺功能。现阶段由于不断的前期地图重复或者错误中断，造成后续的地图无法继续执行。 =》或者先首先完成整个地图流程后，再针对未正确执行的地图重复运行。 =》即使手动选择了从某个地图执行，但是查漏功能似乎仍然从第一个地图开始重复执行。

#540
