### ISSUE TITLE
Character not moving enough to attack the mob

### ISSUE THREAD

**Issue by lampham7** [Starry-Wind/StarRailAssistant#573]
### Problem Description

When i choosed 残响回廊-1 as the start location, the asssitant moved March 7 to a location near to her location in the 1st/2nd screenshot, she attacked/left-clicked few times, the attacks destroyed 1 technique points's purple bottle and ended before the mob went into March 7's sight, she didn't attack it and after seconds she opened map and teleported to the teleport point in the 3rd screenshot
by the way, shouldn't teleporting to the teleport point at the right of the tele point in the 3rd image be better?

### expected behavior

March 7 should have attacked the mob 

### actual behavior

March 7 didn't attack the mob

### screenshot or screen recording

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/77009602/d405f269-7c4d-4636-a8f7-7279286a0470)
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/77009602/f51fd73d-55a6-43b0-92fc-30668e810689)
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/77009602/5664a534-2a67-4fe3-b555-cb71c9158ec4)

### Honkai-Star-Rail version

1.1

### Honkai Star Server

Global

### What equipment do you work on?

PC

### log

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11858697/default.log)
[战斗日志.log](https://github.com/Starry-Wind/StarRailAssistant/files/11858698/default.log)

**Comment by Night-stars-1** [comment]
receive
