### ISSUE TITLE
[功能请求] 识别月卡ui并点击

### ISSUE THREAD

**Issue by SakuraALyCE** [Starry-Wind/StarRailAssistant#574]
### 原因

晚上睡前开启脚本后，凌晨4点会被米系宇宙的新的一天触发领取月卡而导致脚本停止
希望添加点击领取月卡后继续运行脚本

### 功能简述

识别月卡领取ui并点击

### 功能逻辑

当脚本地图识别失败时，和领取月卡的ui进行对比，如果符合则点击屏幕中心点进行领取，然后点击空白区域确认90星穹
因为有可能造成地图定位发生移动，所以当前刷的地图区域可能要进行一次重新进入的操作

**Comment by Night-stars-1** [comment]
#578
