### ISSUE TITLE
[Bug] 6.23晚更新之后出现又反复开关地图情况

### ISSUE THREAD

**Issue by Serein1202** [Starry-Wind/StarRailAssistant#583]
### 问题描述

之前可以正常运行，6.23晚上全部更新之后运行后出现反复开关地图，pc端运行，分辨率已设置成1920x1080

### 预期行为

进入地图，选择星球，选择地图，选择锚点...

### 实际行为

反复开关地图

### 自动锄大地脚本版本

1.6.4

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11859411/default.log)

**Comment by cdcp998** [comment]
在更新下。拉取最新的mian-beta库

**Comment by Night-stars-1** [comment]
窗口左上角不要有其他东西，比如游戏帧数悬浮窗

**Comment by Night-stars-1** [comment]
无人应答，关闭issues

**Comment by Serein1202** [comment]
> 窗口左上角不要有其他东西，比如游戏帧数悬浮窗

感谢回复，问题已解决
