### ISSUE TITLE
[Bug] 雅利洛的星轨地图无法识别，进入不了地图

### ISSUE THREAD

**Issue by bin1129** [Starry-Wind/StarRailAssistant#592]
### 问题描述

如图，雅利洛的星轨航图图片可能是清晰度低或其他原因，在我这无法识别出来进入地图，空间站和仙舟就没问题，自己截图替换图片后正常识别成功
![Snipaste_2023-06-26_13-58-48](https://github.com/Starry-Wind/StarRailAssistant/assets/61070396/3e1160d2-80e8-4351-b751-af19f99352da)

### 预期行为

正确识别进入地图

### 实际行为

卡页面

### 截图或录屏

No response

### 自动锄大地脚本版本

1.6.5

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

无需log

**Comment by Night-stars-1** [comment]
已更换

**Comment by bin1129** [comment]
> > 已更换
> 
> 那个，你弄错了，我换的是jpg那个，把jpg换成了完整的雅利洛-VI，png那个不用换，更新试了下没用，可以换我截的这个
![orientation_3](https://github.com/Starry-Wind/StarRailAssistant/assets/61070396/170f648f-465f-41f9-beb1-6dfad9ff241c)

**Comment by bin1129** [comment]
> 已更换

那个，你弄错了，我换的是jpg那个，把jpg换成了完整的雅利洛-VI，png那个不用换，更新试了下没用，可以换我截的这个
![orientation_3](https://github.com/Starry-Wind/StarRailAssistant/assets/61070396/1ac71a22-db6d-4e7f-aeb2-2a6399d25b38)

**Comment by Night-stars-1** [comment]
jpg从来没有更换过

**Comment by bin1129** [comment]
> jpg从来没有更换过

我感觉我说的挺清楚的啊，就是原来的jpg在我这不行，可能是不完整可能是不清晰，无法识别，我自己在游戏截图把jpg替换了就没问题了

**Comment by Night-stars-1** [comment]
> 

但是jpg文件没动过，这可能是hdr的原因，还是本地换一下吧
