### ISSUE TITLE
[Feature] 想在mac上跑，求支持Polygon3-3.0.9-cp311-cp311-win_amd64.whl的mac版本

### ISSUE THREAD

**Issue by ninjachen** [Starry-Wind/StarRailAssistant#597]
### reason

想在mac上跑，求问这个lib是哪来的吗？ 我去找找它的mac版
(base) ➜  StarRailAssistant git:(main) pip install -r requirements.txt
ERROR: Polygon3-3.0.9-cp311-cp311-win_amd64.whl is not a supported wheel on this platform.

### Brief description of functions

(base) ➜  StarRailAssistant git:(main) pip install -r requirements.txt
ERROR: Polygon3-3.0.9-cp311-cp311-win_amd64.whl is not a supported wheel on this platform.

### functional logic

(base) ➜  StarRailAssistant git:(main) pip install -r requirements.txt
ERROR: Polygon3-3.0.9-cp311-cp311-win_amd64.whl is not a supported wheel on this platform.

**Comment by Night-stars-1** [comment]
这个为本地编译而来，该项目在mac上跑需要修改一部分代码，会修改我想也有能力安装Polygon3
我没有mac设备，无法提供mac端支持

**Comment by ninjachen** [comment]
使用pip install 绕过去了，对python类库不熟，还以为是自己写的lib
`pip install Polygon3`

现在卡在了安装pywin32，估计没办法，放弃了
[ref](https://stackoverflow.com/questions/9233461/pywin32-com-objects-on-mac)

**Comment by Night-stars-1** [comment]
> 使用pip install 绕过去了，对python类库不熟，还以为是自己写的lib `pip install Polygon3`
> 
> 现在卡在了安装pywin32，估计没办法，放弃了 [ref](https://stackoverflow.com/questions/9233461/pywin32-com-objects-on-mac)

pywin32就是要修改的部分，你需要改成mac系统的支持库，只有一小段代码要改

**Comment by coolxll** [comment]
mac跑应该是跑模拟器吧，pywin32那块都加上try catch import就好
