### ISSUE TITLE
program stops running when/after a fight ended

### ISSUE THREAD

**Issue by lampham7** [Starry-Wind/StarRailAssistant#606]
### Problem Description

when/after a fight ended, Honkai_Star_Rail.py stops running (happend at 空间站「黑塔」: 基座舱段-1 and 收容舱段-1)

### expected behavior

program keep running

### actual behavior

program stopped running

### screenshot or screen recording

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/77009602/0ba20076-68f8-425f-9da7-b6f64318a26a)
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/77009602/a67e560d-3a98-4e70-be78-93f280c6eb51)
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/77009602/9142d9ec-b135-42d0-b1db-6826fb2f524f)

### Honkai-Star-Rail version

1.1

### Honkai Star Server

Global

### What equipment do you work on?

PC

### log

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11872273/default.log)
[战斗日志.log](https://github.com/Starry-Wind/StarRailAssistant/files/11872274/default.log)

**Comment by Night-stars-1** [comment]
update the script(StarRailAssistant)
