### ISSUE TITLE
[Feature Request] GUI supporting English language

### ISSUE THREAD

**Issue by lampham7** [Starry-Wind/StarRailAssistant#610]
### reason

Will greatly improve English readers's user experience

### Brief description of functions

Adding English text alongside the original Chinese text of the functions of the GUI, or a option to change GUI's language to English

Names of the 3 Worlds (空间站「黑塔」, 雅利洛-Ⅵ, 仙舟「罗浮」) and theirs Areas (基座舱段-1, 收容舱段-2, ...) should remain the same because the game's language when using the program is Chinese

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/77009602/3281e8ad-d3fd-4902-8cf2-ef82f38d5541)

### functional logic

Adding English text alongside the original Chinese text of the functions of the GUI, or a option to change GUI's language to English

**Comment by Night-stars-1** [comment]
Now the game language can be English, but I'm not sure if it can work properly.
<img width="591" alt="image" src="https://github.com/Starry-Wind/StarRailAssistant/assets/99261160/6497c18f-4d91-4bc4-96d5-9b5e7bd077ec">
