### ISSUE TITLE
連不了bluestack 

### ISSUE THREAD

**Issue by fatkin1012** [Starry-Wind/StarRailAssistant#625]
### 问题描述

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/70193444/a7932fc2-c6c4-47d7-b460-94ec5c3f30d5)

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/70193444/325e3d7a-9eaf-4ffa-a6ec-261de2b27519)

已經打開了模擬器但是顯示沒開
後來手動改了adb的端口和路徑 就顯示 orjson.JSONDecodeError: invalid escaped character in string: line 15 column 30 (char 389)

### 预期行为

應該連模擬器開始掛機

### 实际行为

連接失敗

### 自动锄大地脚本版本

1.6.5

### 星穹铁道区服

国际服

### 运行的客户端

模拟器

### 日志

C:\StarRailAssistant-1.6.5>python Honkai_Star_Rail.py
星穹铁道小助手为开源项目，完全免费
如果你是购买的那么你被骗了
开源仓库地址: https://github.com/Starry-Wind/StarRailAssistant
? 请选择运行平台 大世界
? 请选择起始星球： 空间站「黑塔」
? 请选择起始地图： 基座舱段-1
Honkai_Star_Rail.main:263 - 20230706224019/20230703123705/20230703123705 - 脚本将自动切换至游戏窗口，请保持游戏窗口激活
exceptions.__init__:18 - 20230706224019/20230703123705/20230703123705 - 你游戏没开，我真服了
* server not running *

C:\StarRailAssistant-1.6.5>python Honkai_Star_Rail.py
Traceback (most recent call last):
  File "C:\StarRailAssistant-1.6.5\Honkai_Star_Rail.py", line 23, in <module>
    from get_width import get_width
  File "C:\StarRailAssistant-1.6.5\get_width.py", line 14, in <module>
    from utils.config import init_config_file, modify_json_file, normalize_file_path, CONFIG_FILE_NAME
  File "C:\StarRailAssistant-1.6.5\utils\config.py", line 9, in <module>
    from .log import log
  File "C:\StarRailAssistant-1.6.5\utils\log.py", line 72, in <module>
    language = read_json_file("config.json").get("language", "zh_CN")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\StarRailAssistant-1.6.5\utils\log.py", line 57, in read_json_file
    data = orjson.loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: invalid escaped character in string: line 15 column 30 (char 389)

**Comment by cdcp998** [comment]
新版本已经取消对模拟器的支持。请使用老版本。

**Comment by fatkin1012** [comment]
請問那個版本還支持模擬器
