### ISSUE TITLE
[Bug] 近几日锄大地漏怪问题，临时解决方案，以及传送检测bug

### ISSUE THREAD

**Issue by gezhongshu** [Starry-Wind/StarRailAssistant#633]
### 问题描述

1. 漏怪问题
2. 传送后等待时间过长问题

最新的发布版本中，多人报告出现漏怪问题，此问题在main-beta分支已经简单做了处理。
另外，传送后等待时间过长是calculated.wait_join()函数相关语句出现bug，根据log文件猜测，有以下几点原因
- 选取的取色像素点不合理，位于小地图内部，颜色值不固定
- 由于设备性能等原因，常常会跳过黑屏阶段，从而检测不到进入黑屏状态，这可能是由于代码中存在不合理的人为延迟或其他原因。

**针对以上两个问题，我稍微修改了一下utils/calculated.py文件，临时解决了一下这个问题（下附文件，直接替换本地文件即可）**
**[calculated.zip](https://github.com/Starry-Wind/StarRailAssistant/files/12014545/calculated.zip) *Replace your local file (utils/calculated.py) with this file.***
其中，810行设置的时间可以根据自己设备的性能自行调整，也可以在config文件中修改join_time项实现。

### 预期行为

正常锄大地，传送后正常检测到传送成功。

### 实际行为

漏怪，等待时间异常

### 自动锄大地脚本版本

release 1.6.6

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/12014564/default.log)

**Comment by MrCCecho** [comment]
非常关键的更新，极大提高了效率。

**Comment by zpzyyzp** [comment]
1.6.7出了还需要这个吗？

**Comment by bin1129** [comment]
1.6.5我自己改路线调教成关闭捡漏也连续3天一个不漏了，1.6.7今天试了下黑塔雅利洛都没漏，但仙舟还是漏了不少，我也看出原因了，就是开发者想减少fighting的等待时间，但战斗判定还是不能完全准确

**Comment by gezhongshu** [comment]
> 1.6.7出了还需要这个吗？但是感觉还是漏怪

新版我还没试，新地图出之前我不打算更新了。如果你还是有漏怪的情况可以试着改一改我前面说的那个810行的等待时间，可能你的设备性能不够加载地图比较慢，适当增加一下等待时间就行。
因为我只改了传送检测和战斗检测相关的逻辑，所以如果地图录制人员的路线不够准确也会出现漏怪的情况，这部分就没办法了。不过从我使用的结果来看，漏的很少，估计一共也不超过5个。
