### ISSUE TITLE
[Bug] 传送后地图识别超时，加载时间超过8秒

### ISSUE THREAD

**Issue by bin1129** [Starry-Wind/StarRailAssistant#651]
### 问题描述

传送后地图识别超时，加载时间必定大于8秒，每个地图都是这样
PS：在我这将calculated.py里的wait_join函数中self.compare_lists([0, 0, 222], result)中的222改成214即可加载时间0秒，但0秒加载会吞掉开头一小段跑图操作，导致后续路线全错

### 预期行为

传送后正确识别加载地图，进行跑路

### 实际行为

传送后识别失败，地图加载时间超过8秒

### 自动锄大地脚本版本

1.6.9

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

11:33:12 - INFO	| calculated.click_target:325 - 20230718000947/20230715230112/20230715230112 -  选择地图
11:33:12 - DEBUG	| calculated.part_ocr:706 - 20230718000947/20230715230112/20230715230112 -  {'观景车厢': (1870, 430), '星槎海中枢': (1884, 525), '长乐天': (1856, 624), '流云渡': (1856, 719), '迥星港': (1857, 815), '太下司': (1856, 912), '工造司': (1857, 1007)}
11:33:12 - DEBUG	| calculated.click_target:355 - 20230718000947/20230715230112/20230715230112 -  迥星港
11:33:12 - DEBUG	| calculated.click_target:358 - 20230718000947/20230715230112/20230715230112 -  (1857, 815)
11:33:12 - DEBUG	| calculated.appoint_click:98 - 20230718000947/20230715230112/20230715230112 -  (1857, 815)
11:33:13 - DEBUG	| calculated.appoint_click:104 - 20230718000947/20230715230112/20230715230112 -  [169, 169, 169]
11:33:13 - DEBUG	| calculated.appoint_click:98 - 20230718000947/20230715230112/20230715230112 -  (1857, 815)
11:33:13 - DEBUG	| calculated.appoint_click:104 - 20230718000947/20230715230112/20230715230112 -  [40, 40, 40]
11:33:13 - DEBUG	| map.start_map:129 - 20230718000947/20230715230112/20230715230112 -  temp\map_3-2_point_1.png
11:33:15 - INFO	| calculated.click_target:380 - 20230718000947/20230715230112/20230715230112 -  map_3-2_point_1
11:33:15 - INFO	| calculated.click_target:388 - 20230718000947/20230715230112/20230715230112 -  0.9991486668586731
11:33:15 - DEBUG	| map.start_map:129 - 20230718000947/20230715230112/20230715230112 -  temp\map_3-2_point_2.png
11:33:17 - INFO	| calculated.click_target:380 - 20230718000947/20230715230112/20230715230112 -  map_3-2_point_2
11:33:17 - INFO	| calculated.click_target:388 - 20230718000947/20230715230112/20230715230112 -  0.992050051689148
11:33:18 - DEBUG	| map.start_map:129 - 20230718000947/20230715230112/20230715230112 -  temp\transfer.jpg
11:33:19 - INFO	| calculated.click_target:319 - 20230718000947/20230715230112/20230715230112 -  transfer
11:33:20 - DEBUG	| calculated.part_ocr_other:739 - 20230718000947/20230715230112/20230715230112 -  {'9': (398, 258), '导航': (441, 247), '仙舟「罗浮': (479, 272), '35/180 十': (2029, 259), 'D': (1794, 341), '个11 /11': (558, 356), '、飞星小筑': (1876, 339), '迥星港入口处的小阁，为工造司匠人们': (1969, 417), '准备的换班休息处。': (1868, 456), '2层': (385, 1071), '传送': (1978, 1164), '一': (953, 1184), 'UID:10109589': (417, 1245), '→地图光标移动': (2120, 1245)}
11:33:20 - DEBUG	| calculated.ocr_pos:679 - 20230718000947/20230715230112/20230715230112 -  {'9': (398, 258), '导航': (441, 247), '仙舟「罗浮': (479, 272), '35/180 十': (2029, 259), 'D': (1794, 341), '个11 /11': (558, 356), '、飞星小筑': (1876, 339), '迥星港入口处的小阁，为工造司匠人们': (1969, 417), '准备的换班休息处。': (1868, 456), '2层': (385, 1071), '传送': (1978, 1164), '一': (953, 1184), 'UID:10109589': (417, 1245), '→地图光标移动': (2120, 1245)}
11:33:20 - DEBUG	| calculated.ocr_click:159 - 20230718000947/20230715230112/20230715230112 -  传送
11:33:20 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 214]
11:33:21 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 214]
11:33:21 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 214]
11:33:21 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 214]
11:33:21 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 214]
11:33:21 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:22 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:22 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:22 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:22 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:22 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:23 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:23 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:23 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:23 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:23 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:23 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:24 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:24 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:24 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:24 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [0, 0, 18]
11:33:24 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [106, 111, 140]
11:33:25 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 127, 157]
11:33:25 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [106, 141, 206]
11:33:25 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [106, 128, 134]
11:33:25 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 122, 136]
11:33:26 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 117, 131]
11:33:26 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [106, 113, 131]
11:33:26 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 114, 132]
11:33:26 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 114, 132]
11:33:26 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 114, 132]
11:33:27 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 114, 132]
11:33:27 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 116, 134]
11:33:27 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 114, 132]
11:33:27 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 114, 132]
11:33:27 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 116, 134]
11:33:28 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 114, 132]
11:33:28 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 114, 132]
11:33:28 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 114, 132]
11:33:28 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 114, 132]
11:33:28 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 114, 132]
11:33:29 - DEBUG	| calculated.wait_join:868 - 20230718000947/20230715230112/20230715230112 -  [105, 114, 132]
11:33:29 - INFO	| calculated.wait_join:873 - 20230718000947/20230715230112/20230715230112 -  识别超时
11:33:29 - INFO	| map.start_map:162 - 20230718000947/20230715230112/20230715230112 -  地图加载完毕，加载时间为 8.0612952709198 秒

**Comment by Night-stars-1** [comment]
超时不影响脚本
