### ISSUE TITLE
[Bug] 请在这里简要描述BUG，否则该Issue将直接关闭

### ISSUE THREAD

**Issue by blangero** [Starry-Wind/StarRailAssistant#656]
### 问题描述

无法从3-2切换到3-3（太卜司）， 在寻找3-3地图时失败，（有时会选到3-1流云渡）。
根据log，并未进行星轨航图选择
map.auto_map:104 - 20230718163215/20230715230112/20230715230112 - dict_keys(['Mio', '娜塔莎', '马叉空', '青雀'])
Mio-娜塔莎-马叉空-青雀 - 20230718163215/20230715230112/20230715230112 - 开始太卜司-1锄地
Mio-娜塔莎-马叉空-青雀 - 20230718163215/20230715230112/20230715230112 - 该路线导航作者：雪见璃,夜里无星
Mio-娜塔莎-马叉空-青雀 - 20230718163215/20230715230112/20230715230112 - 感谢每一位无私奉献的作者
Mio-娜塔莎-马叉空-青雀 - 20230718163215/20230715230112/20230715230112 - 进入地图
Mio-娜塔莎-马叉空-青雀 - 20230718163215/20230715230112/20230715230112 - map_3-3
Mio-娜塔莎-马叉空-青雀 - 20230718163215/20230715230112/20230715230112 - 选择地图

### 预期行为

正确选择到3-3 太卜司

### 实际行为

切换地图时无法选择到太卜司。
曾经尝试过讲3-2的地图文件重命名为太卜司地图文件， 仍然无法选择， 怀疑不是图像识别的问题， 是流程问题。（从3-2跳到3-3时出错）

### 自动锄大地脚本版本

1.6.8

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

map.auto_map:104 - 20230718163215/20230715230112/20230715230112 - dict_keys(['Mio', '娜塔莎', '马叉空', '青雀'])
Mio-娜塔莎-马叉空-青雀 - 20230718163215/20230715230112/20230715230112 - 开始太卜司-1锄地
Mio-娜塔莎-马叉空-青雀 - 20230718163215/20230715230112/20230715230112 - 该路线导航作者：雪见璃,夜里无星
Mio-娜塔莎-马叉空-青雀 - 20230718163215/20230715230112/20230715230112 - 感谢每一位无私奉献的作者
Mio-娜塔莎-马叉空-青雀 - 20230718163215/20230715230112/20230715230112 - 进入地图
Mio-娜塔莎-马叉空-青雀 - 20230718163215/20230715230112/20230715230112 - map_3-3
Mio-娜塔莎-马叉空-青雀 - 20230718163215/20230715230112/20230715230112 - 选择地图（此时并未选择并点击‘太卜司’）

**Comment by Night-stars-1** [comment]
请看一下标题写的什么

**Comment by Night-stars-1** [comment]
你提交的不是log而是控制台输出的消息，这确认不了任何问题

**Comment by blangero** [comment]
sorry for the inconvenience, I checked the log file and found that something went wrong with OCR result:

```
 21:58:04 - DEBUG	| calculated.click_target:355 - 20230718163215/20230715230112/20230715230112 -  太卜司
21:58:04 - DEBUG	| calculated.click_target:358 - 20230718163215/20230715230112/20230715230112 -  None
21:58:04 - DEBUG	| calculated.part_ocr:706 - 20230718163215/20230715230112/20230715230112 -  {'观景车厢': (1549, 236), '星槎海中枢': (1562, 332), '长乐天': (1536, 430), '流云渡': (1537, 525), '迥星港': (1537, 622), '太下司': (1536, 719), '工造司': (1537, 814)}
21:58:04 - DEBUG	| calculated.click_target:355 - 20230718163215/20230715230112/20230715230112 -  太卜司
```
太下司  -   太卜司

I updated all local pip packages and will try again later.
