### ISSUE TITLE
[Bug] Can't run anything, always get "TypeError" error

### ISSUE THREAD

**Issue by lampham7** [Starry-Wind/StarRailAssistant#663]
### Problem Description

always get "TypeError" error when running  Honkai_Star_Rail.py or gui.py

Honkai_Star_Rail.py :
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/77009602/6e1fee7b-3dd3-4efd-877d-36d1171a5844)

gui.py : 
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/77009602/0dee1d0c-6657-4b13-80dc-b7c4d57130df)

### expected behavior

program running

### actual behavior

cant run program

### Honkai-Star-Rail version

1.2

### Honkai Star Server

Global

### What equipment do you work on?

PC

### log

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/12100127/default.log)
[战斗日志.log](https://github.com/Starry-Wind/StarRailAssistant/files/12100129/default.log)

**Comment by blangero** [comment]
I think this is a backward compatibility issue, you can try to backup  config.json and delete it (or just rename it) and run again.
