### ISSUE TITLE
[Bug] 1.7版本自动巡径转向会鬼畜，导致后续路线全部错误

### ISSUE THREAD

**Issue by jy02664402** [Starry-Wind/StarRailAssistant#669]
### 问题描述

老版本巡径转向都是瞬间完成，没有冗余动作。1.7开始会在转向时轻微抖动一下，导致路线偏移，大部分地图路线全错，漏怪率高达90%（几乎全漏）。

### 预期行为

转向正常

### 实际行为

转向角色会抖动

### 自动锄大地脚本版本

1.7.0

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/12135926/default.log)

**Comment by Klamist** [comment]
补充：
目前体验上是，新版本按预设json走路的时候，会目视卡顿，导致多走了一点距离，从而走错。

**Comment by Night-stars-1** [comment]
更新
