### ISSUE TITLE
[Bug] 寻路到怪的位置不应该连续攻击

### ISSUE THREAD

**Issue by sbant** [Starry-Wind/StarRailAssistant#681]
### 问题描述

由于星铁的角色攻击时大多会有位移（比如青雀往前，娜塔莎往后），等待怪物开战或者没有怪物时连续攻击会使角色偏离原路线

### 预期行为

到了怪物点后最多攻击2次
看过原来老版本的代码，等待10秒，每次攻击间隔3秒，还是会攻击4次
我个人尝试过改为5秒延迟（等待期间攻击2次），稳定性提升不少

我的意思是不一定要等足一定时间（比如10秒），而是等待期间不要连续攻击

### 实际行为

目前的版本(v1.7.4)在等待期间会不停连续攻击，偏移很多位置

### 自动锄大地脚本版本

v1.7.4

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

不需要

**Comment by jy02664402** [comment]
只要连续攻击不导致错位都还好，但是间隔3秒会因为角色攻击完以后的动作，导致轻微位移，概率发生之后路线全错
