### ISSUE TITLE
[功能请求] 修改项目文档以帮助新手

### ISSUE THREAD

**Issue by DLmaster361** [Starry-Wind/StarRailAssistant#688]
### 原因

部分新手安装吃力

### 功能简述

更新项目文档

### 功能逻辑

md文件：
##常见问题
- 1.依赖下载速度过慢：在更换国内pip源时，改用清华源，代码为config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple/
- 2.错误提示ModuleNotFoundError: No module named 'ruamel'：通过pip install ruamel.yaml安装缺失的库。如果遇到类似报错，可以自行百度解决
- 3.start.exe无法使用：参考百度网盘链接：https://pan.baidu.com/s/170xCU1y6-f6f6mvrAYBnQQ?pwd=amsk 提取码：amsk

### 实现参考

md文件：
##常见问题
- 1.依赖下载速度过慢：在更换国内pip源时，改用清华源，代码为config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple/
- 2.错误提示ModuleNotFoundError: No module named 'ruamel'：通过pip install ruamel.yaml安装缺失的库。如果遇到类似报错，可以自行百度解决
- 3.start.exe无法使用：参考百度网盘链接：https://pan.baidu.com/s/170xCU1y6-f6f6mvrAYBnQQ?pwd=amsk 提取码：amsk

**Comment by Shuntw6096** [comment]
我來分享我的方法, 我使用win11
1. 請先安裝python, 並更新pip
2. 為了方便, 在桌面開啟終端(cmd)
3. 安裝virtualenv, ```pip install virtualenv```
4. 建立虛擬環境, ```python -m virtualenv star_rail```, star_rail是虛擬環境名稱
5. 此時桌面有star_rail目錄, 進入該目錄, 創建```pip.ini```這個檔案, 並用文字編輯器打開, 輸入或貼上後存檔```global.index-url=https://mirrors.aliyun.com/pypi/simple```
6. 開啟虛擬環境(我在star_rail目錄開啟終端), 輸入```.\scripts\activate```, 此時最左邊有```(star_rail)```
7. 此時可能被拒絕執行, 請參考[這個](https://blog.csdn.net/qq_32944491/article/details/123698540), 做完重開終端做第6步
8. 輸入```pip config list```會顯示```global.index-url=https://mirrors.aliyun.com/pypi/simple```
9. 把StarRailAssistant拉近star_rail目錄解壓縮, 並進入目錄```cd .\StarRailAssistant目錄名稱```, 底下有```requirements.txt```
10. 輸入```pip install -r .\requirements.txt```安裝環境
11. ```python .\Honkai_Star_Rail.py```

**Comment by KawaiiSh1zuku** [comment]
> 我來分享我的方法, 我使用win11
> 
> 1. 請先安裝python, 並更新pip
> 2. 為了方便, 在桌面開啟終端(cmd)
> 3. 安裝virtualenv, `pip install virtualenv`
> 4. 建立虛擬環境, `python -m virtualenv star_rail`, star_rail是虛擬環境名稱
> 5. 此時桌面有star_rail目錄, 進入該目錄, 創建`pip.ini`這個檔案, 並用文字編輯器打開, 輸入或貼上後存檔`global.index-url=https://mirrors.aliyun.com/pypi/simple`
> 6. 開啟虛擬環境(我在star_rail目錄開啟終端), 輸入`.\scripts\activate`, 此時最左邊有`(star_rail)`
> 7. 此時可能被拒絕執行, 請參考[這個](https://blog.csdn.net/qq_32944491/article/details/123698540), 做完重開終端做第6步
> 8. 輸入`pip config list`會顯示`global.index-url=https://mirrors.aliyun.com/pypi/simple`
> 9. 把StarRailAssistant拉近star_rail目錄解壓縮, 並進入目錄`cd .\StarRailAssistant目錄名稱`, 底下有`requirements.txt`
> 10. 輸入`pip install -r .\requirements.txt`安裝環境
> 11. `python .\Honkai_Star_Rail.py`


不用在桌面，在文件资源管理器的地址栏输入`cmd`会自动打开当前目录的命令提示符

**Comment by jelly0925** [comment]
感觉大佬

**Comment by Night-stars-1** [comment]
对于1，目前的国内源阿里云是最好用的，我不推荐使用其他源，同步慢
对于2，我们没有使用这个库
