### ISSUE TITLE
[功能请求] 支持多设备/虚拟机通过远程桌面/moonlight等完全隔离操控

### ISSUE THREAD

**Issue by Waximell** [Starry-Wind/StarRailAssistant#696]
### 原因

看到了支持文档中后台运行的相关描述，我想到通过完全物理隔离小助手与游戏本体，既然软件不涉及读取内存等操作，仅通过模拟键鼠操控的话，理论上应该存在实现的可能性。（主要是怂，怕被封号）

### 功能简述

现在的软件要求在本地运行游戏本体，我希望它可以检测远程桌面/moonlight/amdlink是否运行（至于远程PC内是否运行游戏本体显然无法检测，那就交给用户自行打开吧）

### 功能逻辑

在PC1中安装好小助手，通过远程桌面/moonlight等连接PC2，PC2中运行星铁，小助手完全通过在PC1的远程桌面/moonlight所显示的画面模拟键鼠操控PC2中的游戏本体。以及，PC1可否为虚拟机，在虚拟机内通过moonlight等来操作物理机运行的星铁。（既然涉及了虚拟机，是否可以直接打包个docker镜像之类的）

**Comment by Akalamianxiong** [comment]
用别怕 封别叫

**Comment by Eisaichen** [comment]
所以为什么不直接在PC2运行小助手呢，这个本来就无需任何开发就能实现
<img width="1487" alt="Untitled" src="https://github.com/Starry-Wind/StarRailAssistant/assets/12467320/347b552a-954c-42b7-a492-864825adabb9">
