### ISSUE TITLE
[Feature] english support

### ISSUE THREAD

**Issue by dyewitness** [Starry-Wind/StarRailAssistant#70]
### 问题描述

你好！
感谢您公开脚本！ 我有几个问题。
1. 以后有计划支持英文吗？
2. 使用脚本安全吗？ 如果不是，你如何保护自己？
3. 是否可以在 Discord 上与您联系，那里会有一个小组吗？

我不会说中文，我用谷歌翻译。

### 是否使用三月七跑图

- [ ] 是
- [ ] 否

### 日志

-

**Comment by Starry-Wind** [comment]
1：是的，以后有计划会支持英文。但是目前还在测试稳定性，现在暂时没有这么多时间精力去开发英文版本。
2：任何辅助都可能存在风险，并不能确保100%安全，后期我们会考虑这个问题。
3：我们暂无Discord组，我们将会建立。
感谢issue

**Comment by Night-stars-1** [comment]
1. The script is unstable at present, and there are supporting plans in the future.
2. We can't guarantee the security of the script, because the script simulates keyboard and mouse operations, which can be detected. But the script has no dangerous code.
3. We are going to add telegram group chat.

**Comment by apple050620312** [comment]
Discord群組的話就有點複雜了
Discord will be too complicated
我覺得用Telegram就很不錯了
I think Telegram is enough now

**Comment by michael-pptf** [comment]
If all he needed was an english prompt interface and english logs, that could be done rather easily. I just don't know to what extent he meant by having an english version.

**Comment by apple050620312** [comment]
But the game language still have to be Chinese Simplified
