### ISSUE TITLE
快速简单的配置RDPWarp

### ISSUE THREAD

**Issue by yige-yigeren** [Starry-Wind/StarRailAssistant#701]
### 原因

关于远程的一点建议
RDPwarp可能比较难搞

### 功能简述

简化了部署RDPwarp的一些功能

### 功能逻辑

我之前有写过一个带了安装和国内网络优化的版本
并且可以配置随系统自动更新配置文件

### 实现参考

这是我之前项目的链接
https://github.com/yige-yigeren/rdpwrap_AutoUpdate_CN

**Comment by Night-stars-1** [comment]
好的，感谢
