### ISSUE TITLE
1.3版本更新后，一场战斗结束后需要等很久角色才能开始向下一个怪移动

### ISSUE THREAD

**Issue by scyang0457** [Starry-Wind/StarRailAssistant#704]
### 问题描述

1.3版本更新后，一场战斗结束后需要等很久角色才能开始向下一个怪移动。想请问各位大佬怎么解决(ﾉ_ _)ﾉ

### 预期行为

一场战斗结束后，角色立即向下一个目标地点移动

### 实际行为

角色呆在原地很长时间，要等到“战斗超时”后才会向下一个目标移动

### 截图或录屏

![2023-08-30 19_36_34-2023-08-30 17_46_18-管理员_ Windows PowerShell jpg ‎- 照片](https://github.com/Starry-Wind/StarRailAssistant/assets/143587886/be33836f-df2c-4996-81ba-58ab864fc6d3)
![2023-08-30 19_38_04-崩坏：星穹铁道](https://github.com/Starry-Wind/StarRailAssistant/assets/143587886/5d1f0b5d-d185-4443-b2bf-e7b719044825)

### 自动锄大地脚本版本

v1.7.2

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

[战斗日志.log](https://github.com/Starry-Wind/StarRailAssistant/files/12475181/default.log)

**Comment by ChineseBeanLin** [comment]
超时应该是因为战斗判断方法是这个底部提示没了，原来是有这个提示条的
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/24269792/a2b537a7-ad11-4af5-ab94-daf3b827f481)
1.3加了这个，默认是关闭的，打开就行了
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/24269792/25b561ab-8dc4-4779-8a7a-7fee33a86278)

**Comment by scyang0457** [comment]
好家伙，没想到是这样，谢谢大佬(ﾉ_ _)ﾉ
