### ISSUE TITLE
[Bug] ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

### ISSUE THREAD

**Issue by AuthurExcalbern** [Starry-Wind/StarRailAssistant#705]
### 问题描述

脚本起动报错
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

### 预期行为

正常执行脚本

### 实际行为

脚本未执行

### 自动锄大地脚本版本

1.7.3

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/12701937/default.log)

**Comment by DouyaBula** [comment]
我也遇到了这个问题了，应该是依赖库的问题

解决方法如下：
（1）找到`python根目录\Lib\site-packages\cnocr\ppocr\utility.py`的第168行，`python根目录\Lib\site-packages\cnstd\ppocr\utility.py`和`python根目录\Lib\site-packages\cnocr\recognizer.py`的第191行。
如果安装库的版本不同，行数也可能不同，最好根据报错找这三个文件的出错行。

（2）将这三行代码的`InferenceSession(***)`修改为`InferenceSession(***, providers=['AzureExecutionProvider', 'CPUExecutionProvider'])`。

**Comment by AuthurExcalbern** [comment]
good job，按报错提示修改依赖库后已经可以成功运行
