### ISSUE TITLE
[Bug] exceptions.__init__:20 - v1.8.4/0/20231001231617 - [资源文件更新]picture\home.png校验失败, 程序退出

### ISSUE THREAD

**Issue by Wang-zhechao** [Starry-Wind/StarRailAssistant#725]
### 问题描述

exceptions.__init__:20 - v1.8.4/0/20231001231617 - [资源文件更新]picture\home.png校验失败, 程序退出

### 预期行为

正常跟新

### 实际行为

exceptions.__init__:20 - v1.8.4/0/20231001231617 - [资源文件更新]picture\home.png校验失败, 程序退出

### 自动锄大地脚本版本

StarRailAssistant-1.8.4

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

exceptions.__init__:20 - v1.8.4/0/20231001231617 - [资源文件更新]picture\home.png校验失败, 程序退出

**Comment by Wang-zhechao** [comment]
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/55741988/d48f2a3c-7c54-4f42-a4a9-f68eac1662c6)

**Comment by AjiuQUQ** [comment]
相同问题

**Comment by jelly0925** [comment]
相同问题

**Comment by Night-stars-1** [comment]
#726 
已修复
