### ISSUE TITLE
[Bug] 游戲分辨率設置了1920x1080 還是運行不了

### ISSUE THREAD

**Issue by geniusleung** [Starry-Wind/StarRailAssistant#731]
### 问题描述

我按照設置了游戲分辨率，打開程序后出現“Real resolution:1936 x 1119 x 1.0 False"

請問怎麽可以解決，謝謝！

### 预期行为

不知道 

### 实际行为

Real resolution:1936 x 1119 x 1.0 False

### 截图或录屏

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/87888909/465d792d-9c0d-4eb2-a8aa-4105fd40e665)

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/87888909/573229ff-451c-4538-b6e6-d9ebd7dd59d5)

### 自动锄大地脚本版本

1.8.4

### 星穹铁道区服

国际服

### 运行的客户端

PC

### 日志

Real resolution:1936 x 1119 x 1.0 False

**Comment by Night-stars-1** [comment]
如果你是1080的屏幕，要全屏运行

**Comment by geniusleung** [comment]
> 如果你是1080的屏幕，要全屏运行

我的屏幕是1560x1440的

**Comment by geniusleung** [comment]
然後我試過設置1080全屏幕，也是出現同樣的錯誤
