### ISSUE TITLE
NotImplementedError: ('densenet_lite_114-fc', 'onnx') is not a downloadable model

### ISSUE THREAD

**Issue by t1i6xup6** [Starry-Wind/StarRailAssistant#776]
### 问题描述

進入遊戲之後第一次打開腳本 設定完一些代理之後重開 選完地圖之後應該就要開始鋤大地了但是沒有執行

### 预期行为

開始鋤大地???

### 实际行为

什麼都沒動，python程式退出

### 截图或录屏

![螢幕擷取畫面 2023-12-25 230449](https://github.com/Starry-Wind/StarRailAssistant/assets/67141169/d5b71185-faf0-4b66-82b1-438eda18a3cc)

### 自动锄大地脚本版本

不知道從哪看

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/13766550/default.log)

**Comment by fanshu-520** [comment]
https://github.com/Starry-Wind/StarRailAssistant/issues/777#issuecomment-1874967710

**Comment by Sawyer-Z** [comment]
> [#777 (comment)](https://github.com/Starry-Wind/StarRailAssistant/issues/777#issuecomment-1874967710)

并不能解决，仍然报错
